import { describe, it, expect } from "vitest";
import { render } from "@testing-library/react";
import React from "react";
import {
  X,
  Check,
  CheckCircle2,
  Loader2,
  AlertCircle,
  AlertTriangle,
  Sparkles,
  FileText,
  Bookmark,
  Brain,
  SettingsIcon,
  Lock,
  Unlock,
  Search,
  Download,
  Share2,
  HelpCircle,
  Mic,
  MicOff,
  RefreshCw,
  RotateCcw,
  Copy,
  Save,
  Trash2,
  Plus,
  Folder,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ExternalLink,
  LinkIcon,
  Globe,
  Activity,
  Clock,
  Users,
  Menu,
  Sun,
  Moon,
  Palette,
  Database,
  Wifi,
  WifiOff,
  Shield,
  Key,
  Zap,
  ImageIcon,
  Play,
  Pause,
  Volume2,
  Music,
  History,
  Eye,
  Tags,
  Tag,
  Wand2,
  Type,
  Maximize2,
  Minimize2,
  Coffee,
  AlignLeft,
  AlignCenter,
  AlignJustify,
  Timer,
  Network,
  BarChart3,
  Scissors,
  Info,
  Filter,
  Calendar,
  LayoutDashboard,
  MessageSquare,
  Send,
  Bot,
  User,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ArrowUpDown,
  CheckSquare,
  Keyboard,
  Command,
  Cpu,
  HardDrive,
  GitBranch,
  BrainCircuit,
  SquareFunction,
  MapIcon,
  LayoutGrid,
  List,
  MoreVertical,
  FileUp,
  Home,
} from "../../components/icons";

const iconComponents = [
  { name: "X", Component: X },
  { name: "Check", Component: Check },
  { name: "CheckCircle2", Component: CheckCircle2 },
  { name: "Loader2", Component: Loader2 },
  { name: "AlertCircle", Component: AlertCircle },
  { name: "AlertTriangle", Component: AlertTriangle },
  { name: "Sparkles", Component: Sparkles },
  { name: "FileText", Component: FileText },
  { name: "Bookmark", Component: Bookmark },
  { name: "Brain", Component: Brain },
  { name: "SettingsIcon", Component: SettingsIcon },
  { name: "Lock", Component: Lock },
  { name: "Unlock", Component: Unlock },
  { name: "Search", Component: Search },
  { name: "Download", Component: Download },
  { name: "Share2", Component: Share2 },
  { name: "HelpCircle", Component: HelpCircle },
  { name: "Mic", Component: Mic },
  { name: "MicOff", Component: MicOff },
  { name: "RefreshCw", Component: RefreshCw },
  { name: "RotateCcw", Component: RotateCcw },
  { name: "Copy", Component: Copy },
  { name: "Save", Component: Save },
  { name: "Trash2", Component: Trash2 },
  { name: "Plus", Component: Plus },
  { name: "Folder", Component: Folder },
  { name: "ChevronRight", Component: ChevronRight },
  { name: "ChevronDown", Component: ChevronDown },
  { name: "ChevronUp", Component: ChevronUp },
  { name: "ExternalLink", Component: ExternalLink },
  { name: "LinkIcon", Component: LinkIcon },
  { name: "Globe", Component: Globe },
  { name: "Activity", Component: Activity },
  { name: "Clock", Component: Clock },
  { name: "Users", Component: Users },
  { name: "Menu", Component: Menu },
  { name: "Sun", Component: Sun },
  { name: "Moon", Component: Moon },
  { name: "Palette", Component: Palette },
  { name: "Database", Component: Database },
  { name: "Wifi", Component: Wifi },
  { name: "WifiOff", Component: WifiOff },
  { name: "Shield", Component: Shield },
  { name: "Key", Component: Key },
  { name: "Zap", Component: Zap },
  { name: "ImageIcon", Component: ImageIcon },
  { name: "Play", Component: Play },
  { name: "Pause", Component: Pause },
  { name: "Volume2", Component: Volume2 },
  { name: "Music", Component: Music },
  { name: "History", Component: History },
  { name: "Eye", Component: Eye },
  { name: "Tags", Component: Tags },
  { name: "Tag", Component: Tag },
  { name: "Wand2", Component: Wand2 },
  { name: "Type", Component: Type },
  { name: "Maximize2", Component: Maximize2 },
  { name: "Minimize2", Component: Minimize2 },
  { name: "Coffee", Component: Coffee },
  { name: "AlignLeft", Component: AlignLeft },
  { name: "AlignCenter", Component: AlignCenter },
  { name: "AlignJustify", Component: AlignJustify },
  { name: "Timer", Component: Timer },
  { name: "Network", Component: Network },
  { name: "BarChart3", Component: BarChart3 },
  { name: "Scissors", Component: Scissors },
  { name: "Info", Component: Info },
  { name: "Filter", Component: Filter },
  { name: "Calendar", Component: Calendar },
  { name: "LayoutDashboard", Component: LayoutDashboard },
  { name: "MessageSquare", Component: MessageSquare },
  { name: "Send", Component: Send },
  { name: "Bot", Component: Bot },
  { name: "User", Component: User },
  { name: "ArrowRight", Component: ArrowRight },
  { name: "ArrowLeft", Component: ArrowLeft },
  { name: "ArrowUp", Component: ArrowUp },
  { name: "ArrowDown", Component: ArrowDown },
  { name: "ArrowUpDown", Component: ArrowUpDown },
  { name: "CheckSquare", Component: CheckSquare },
  { name: "Keyboard", Component: Keyboard },
  { name: "Command", Component: Command },
  { name: "Cpu", Component: Cpu },
  { name: "HardDrive", Component: HardDrive },
  { name: "GitBranch", Component: GitBranch },
  { name: "BrainCircuit", Component: BrainCircuit },
  { name: "SquareFunction", Component: SquareFunction },
  { name: "MapIcon", Component: MapIcon },
  { name: "LayoutGrid", Component: LayoutGrid },
  { name: "List", Component: List },
  { name: "MoreVertical", Component: MoreVertical },
  { name: "FileUp", Component: FileUp },
  { name: "Home", Component: Home },
];

describe("Iconos re-exportados de lucide-react", () => {
  iconComponents.forEach(({ name, Component }) => {
    it(`${name} renders as SVG with className size-4`, () => {
      const { container } = render(<Component className="size-4" />);
      const svg = container.querySelector("svg");
      expect(svg).toBeDefined();
      expect(svg?.classList.contains("size-4")).toBe(true);
    });
  });

  it("all icons have a displayName", () => {
    iconComponents.forEach(({ name, Component }) => {
      expect((Component as any).displayName || Component.name).toBeDefined();
    });
  });

  it("icons accept size props", () => {
    iconComponents.slice(0, 5).forEach(({ Component }) => {
      const { container } = render(<Component size={24} />);
      const svg = container.querySelector("svg");
      expect(svg).toBeDefined();
      expect(
        svg?.getAttribute("width") || svg?.getAttribute("stroke-width"),
      ).toBeDefined();
    });
  });

  it("icons can have a custom color", () => {
    const { container } = render(<X color="red" />);
    const svg = container.querySelector("svg");
    expect(svg?.getAttribute("stroke")).toBe("red");
  });
});
