import { readBoundedInteger } from "../proxy-utils";

export const PORT = Number(process.env.PORT ?? 8787);
export const HOST = process.env.HOST ?? "0.0.0.0";
export const SERVER_INSTANCE_ID = crypto.randomUUID();
export const SIGNALING_IP_HASH_SALT = process.env.SIGNALING_IP_HASH_SALT || SERVER_INSTANCE_ID;
export const TRUST_PROXY = process.env.TRUST_PROXY === "1" || process.env.TRUST_PROXY === "true";
export const SIGNALING_ADMIN_TOKEN = process.env.SIGNALING_ADMIN_TOKEN ?? "";
export const HEARTBEAT_INTERVAL_MS = (() => { const raw = Number(process.env.HEARTBEAT_INTERVAL_MS ?? 30_000); if (!Number.isFinite(raw)) return 30_000; return Math.min(Math.max(Math.round(raw), 1_000), 86_400_000); })();
export const WS_ALLOWED_ORIGINS = new Set((process.env.WS_ALLOWED_ORIGINS ?? "").split(",").map((o) => o.trim()).filter(Boolean));
export const MAX_CONNECTIONS = readBoundedInteger(process.env.MAX_CONNECTIONS, 512, 1, 10_000);
export const MAX_ROOMS = readBoundedInteger(process.env.MAX_ROOMS, 2_048, 1, 100_000);
export const MAX_PEERS_PER_ROOM = Math.min(readBoundedInteger(process.env.MAX_PEERS_PER_ROOM, 64, 1, 1_024), MAX_CONNECTIONS);
export const MAX_PAYLOAD_BYTES = readBoundedInteger(process.env.MAX_PAYLOAD_BYTES, 1024 * 1024, 1_024, 4 * 1024 * 1024);
export const JOIN_LIMIT = readBoundedInteger(process.env.JOIN_LIMIT, 120, 1, 10_000);
export const MAX_ROOM_SECRET_LENGTH = 128;
export const MAX_PEER_ID_LENGTH = 128;
export const MAX_SIGNAL_AUTH_LENGTH = 64;
export const MAX_SIGNAL_DATA_BYTES = 256 * 1024;
export const SIGNAL_REPLAY_WINDOW_MS = readBoundedInteger(process.env.SIGNAL_REPLAY_WINDOW_MS, 30_000, 1_000, 300_000);
export const MAX_RECENT_SIGNALS_PER_ROOM = readBoundedInteger(process.env.MAX_RECENT_SIGNALS_PER_ROOM, 256, 16, 4_096);
export const JOIN_WINDOW_MS = readBoundedInteger(process.env.JOIN_WINDOW_MS, 60_000, 1_000, 86_400_000);
export const MAX_JOIN_RATE_ENTRIES = readBoundedInteger(process.env.MAX_JOIN_RATE_ENTRIES, 10_000, 1, 100_000);
export const TURN_RELAY_HOST = (() => { const host = (process.env.TURN_RELAY_HOST ?? "").trim(); const isDnsOrIpv4 = /^[A-Za-z0-9.-]+$/.test(host); const isBracketedIpv6 = /^\[[0-9A-Fa-z:]+\]$/.test(host); if (host.length === 0 || host.length > 253 || (!isDnsOrIpv4 && !isBracketedIpv6)) return ""; return host; })();
export const TURN_STATIC_AUTH_SECRET = process.env.TURN_STATIC_AUTH_SECRET ?? "";
export const TURN_PORT = readBoundedInteger(process.env.TURN_PORT, 3478, 1, 65_535);
export const TURN_TLS_PORT = readBoundedInteger(process.env.TURN_TLS_PORT, 5349, 1, 65_535);
export const TURN_TTL_SECONDS = readBoundedInteger(process.env.TURN_TTL, 15 * 60, 5 * 60, 60 * 60);
export const ENFORCE_SIGNAL_HMAC = !((process.env.ENFORCE_SIGNAL_HMAC === "0" || process.env.ENFORCE_SIGNAL_HMAC === "false") && (process.env.NODE_ENV === "development" || process.env.NODE_ENV === "test"));
export const CLOSE_POLICY = 1008;
export const CLOSE_OVERLOAD = 1013;
export const MAX_FORWARDED_IP_LENGTH = 128;
export const ROOM_ID_PATTERN = /^[A-Za-z0-9._-]{1,64}$/;
export const CSP_REPORT_MAX = readBoundedInteger(process.env.CSP_REPORT_MAX, 200, 1, 10_000);
export const CSP_REPORT_LIMIT = readBoundedInteger(process.env.CSP_REPORT_LIMIT, 30, 1, 10_000);
export const CSP_REPORT_WINDOW_MS = readBoundedInteger(process.env.CSP_REPORT_WINDOW_MS, 60_000, 1_000, 86_400_000);
export const CSP_REPORT_FILE = process.env.CSP_REPORT_FILE ?? "";
export const CSP_REPORT_ADMIN_TOKEN = process.env.CSP_REPORT_ADMIN_TOKEN ?? "";
export const CSP_REPORT_ALLOWED_ORIGINS = new Set((process.env.CSP_REPORT_ALLOWED_ORIGIN ?? "").split(",").map((o) => o.trim()).filter(Boolean));
export const CSP_REPORT_IP_HASH_SALT = process.env.CSP_REPORT_IP_HASH_SALT || SERVER_INSTANCE_ID;
export const CSP_REPORT_BODY_MAX_BYTES = readBoundedInteger(process.env.CSP_REPORT_BODY_MAX_BYTES, 16_384, 1_024, 4 * 1024 * 1024);
export const CSP_REPORT_RATE_MAX_ENTRIES = readBoundedInteger(process.env.CSP_REPORT_RATE_MAX_ENTRIES, 10_000, 100, 100_000);
export const CSP_REPORT_WEBHOOK_ALLOW_HTTP = process.env.CSP_REPORT_WEBHOOK_ALLOW_HTTP === "1" && process.env.NODE_ENV !== "production";
export const CSP_REPORT_WEBHOOK_URL = (() => { const raw = process.env.CSP_REPORT_WEBHOOK_URL?.trim() ?? ""; if (!raw) return ""; const protocolOk = /^https:\/\//i.test(raw) || (CSP_REPORT_WEBHOOK_ALLOW_HTTP && /^http:\/\//i.test(raw)); if (!protocolOk) return ""; return raw; })();
export const CSP_REPORT_WEBHOOK_INTERVAL_MS = readBoundedInteger(process.env.CSP_REPORT_WEBHOOK_INTERVAL_MS, 15_000, 250, 86_400_000);
export const CSP_REPORT_WEBHOOK_BATCH_MAX = readBoundedInteger(process.env.CSP_REPORT_WEBHOOK_BATCH_MAX, 20, 1, 1_000);
export const CSP_REPORT_WEBHOOK_MAX_ATTEMPTS = readBoundedInteger(process.env.CSP_REPORT_WEBHOOK_MAX_ATTEMPTS, 3, 1, 10);
export const CSP_REPORT_WEBHOOK_QUEUE_MAX = readBoundedInteger(process.env.CSP_REPORT_WEBHOOK_QUEUE_MAX, 1_000, 1, 100_000);
export const CSP_REPORT_WEBHOOK_TIMEOUT_MS = readBoundedInteger(process.env.CSP_REPORT_WEBHOOK_TIMEOUT_MS, 5_000, 1_000, 60_000);
export const HTTP_SECURITY_HEADERS: Readonly<Record<string, string>> = { "X-Content-Type-Options": "nosniff", "X-Frame-Options": "DENY", "Referrer-Policy": "no-referrer", "Permissions-Policy": "camera=(), geolocation=(), microphone=()", "Content-Security-Policy": "default-src 'none'; base-uri 'none'; frame-ancestors 'none'" };
