// Generated by scripts/generate-license-keys.mjs — DO NOT EDIT BY HAND.
// Regenerate: node scripts/generate-license-keys.mjs --write
// Gate:       npm run check:license-keys (--check)
//
// PUBLIC VERIFICATION KEY ONLY. The matching private signing key is a
// server-side secret (see server/src/license-signing.ts). The client never
// signs — it only verifies state signed by the signing service.
//
// LICENSE_FIXTURE_PAYLOAD / LICENSE_FIXTURE_SIGNATURE are a committed
// prove-the-keypair pair: the signature is produced by the matching private
// key, so check:license-keys and the verify tests can assert that this
// public key actually validates real signatures without the private key
// being committed.
export const LICENSE_PUBLIC_KEY_SPKI =
  "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuTSUMP/aVL5NWM+XeujNElLe7cjscfgsjrrMqXqQveJBNBpdo9wJW8jDCcoHjtpWxNF+YCcbknhYWpGtz8TZ+7kDt2+dSzHR8q0zUTCeiK80PxZftlOqj1D8oDo3bz0GczLFTbV+2iikKOt3YBp3OWgMm8QrSYCOP8CjDibR9mz53SHKxragO6l9GG4ZeR+2DUHNgw6LpROMFpvDax+XyQU4hRHmjmGy4kwbp9aYg5pj93YEAKAPitHn44s2zWXyY3EYN8I4JpGrsJTPTSD9xNp+hUmDs2vmH5U2Bici144vAiZyRQIN+JrJuAjvrj6myekPPtbMxMo3JgM7PLIHoQIDAQAB";
export const LICENSE_FIXTURE_SIGNATURE =
  "OaGEIPcgRppPsuqe4qUd3QUw1IJgbVYO+ZQVZFqTZdY4HtRdAPSdp5kUelMy0FCtXbh7e500sVSISVSh9WnIvFZ3ABpXqRB77uyDmgIvqiAE5lDg7YHUiQOjNXKiWLFCoK9fzlWAuclEEAOQuhZUavwYCk+Kge+gq2jL5JhYbIoPsus/qr3pBbeLDhuDFjH8K2WkfRKyA/5n3kg3t4SPsY+cZQB/i4RhHaV5+TX/hMZvEidP2utD0uZ7CfqvmzBLEvUnco1iRXw+J6VCdV+DqdozBuWk3tb9M41U4kLXaoLaN/mMeluf5M2NBeTkC/1snt8depKKuAMHcNHVZpVlpg==";
export const LICENSE_FIXTURE_PAYLOAD = {
  "v": 1,
  "deviceId": "fixture-device-0001",
  "validatedAt": 1700000000000,
  "expiresAt": 1800000000000,
  "activationsLeft": 3,
  "instanceId": "fixture-instance-0001"
} as const;
