/**
 * Model Integrity Verifier
 * ────────────────────────
 * Pins the SHA-256 digest of every model file the app downloads from a
 * remote model host (Hugging Face by default, or a self-hosted mirror that
 * preserves the same repository path layout). The pin list lives in
 * `src/data/modelDigests.json`, generated by
 * `scripts/pin-model-digests.mjs` from the LFS `oid sha256:` pointers — the
 * exact value transformers.js itself derives, so a downloaded file that does
 * not hash to the pinned digest is byte-for-byte the wrong file.
 *
 * Integration with transformers.js:
 *   transformers.js supports a custom Web-Cache-like object via
 *   `env.useCustomCache` / `env.customCache` (source: src/utils/cache.js).
 *   Every model download flows through `cache.put(url, response)`. We install
 *   a verifying cache that hashes the bytes BEFORE they are stored; a digest
 *   mismatch (or, in production, an unpinned model-file URL from a pinned
 *   host) throws, which aborts the model load — fail-closed. Files that are
 *   not model files (same-origin app assets, ONNX-runtime WASM shipped in
 *   our bundle) are stored unverified; those are covered by bundle
 *   integrity (src/utils/bundleIntegrity.ts) and SRI.
 *
 * Self-hosted mirrors: point `VITE_MODEL_SELF_HOST_URL` at your mirror.
 * Digests are keyed by repository path, not by origin, so any host serving
 * the same bytes validates.
 *
 * Privacy: fully local. No bytes leave the device beyond the model download
 * itself. Failures are logged (no PII).
 */

import { logRateLimited } from "./boundedLog";
import { logger } from "./logger";
// resolveJsonModule is enabled (tsconfig.json); Vite bundles the JSON.
import modelDigests from "../data/modelDigests.json";

interface ModelDigestManifest {
  schemaVersion: number;
  pinnedAt: string;
  remoteHost: string;
  models: Record<
    string,
    { revision: string; files: Record<string, string> }
  >;
}

const manifest = modelDigests as ModelDigestManifest;

export class ModelIntegrityError extends Error {
  constructor(url: string, reason: string) {
    super(`[MODEL INTEGRITY] ${url} — ${reason}`);
    this.name = "ModelIntegrityError";
  }
}

const VERIFIED_CACHE_NAME = "bmf-model-integrity";
const MAX_MODEL_CACHE_ENTRIES = 50;
const MAX_MODEL_CACHE_BYTES = 1024 * 1024 * 1024;

function sha256Hex(bytes: ArrayBuffer | ArrayBufferView): Promise<string> {
  const view = bytes instanceof ArrayBuffer
    ? new Uint8Array(bytes)
    : new Uint8Array(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const data = new Uint8Array(view.byteLength);
  data.set(view);
  return crypto.subtle.digest("SHA-256", data).then((hashBuffer) => {
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");
  });
}

/** Self-host override read at call time so CI/tests can stub it. */
function getSelfHostUrl(): string {
  return import.meta.env.VITE_MODEL_SELF_HOST_URL || "";
}

/**
 * Resolve the pinned digest for a model download URL, or null when the URL
 * is not a pinned model file (app asset, ONNX-runtime WASM, etc.).
 * Path layout: `/{modelOwner}/{modelName}/resolve/{revision}/{file}`.
 */
export function getPinnedDigest(url: string): string | null {
  let parsed: URL;
  try {
    parsed = new URL(url);
  } catch {
    return null;
  }
  const segments = parsed.pathname.split("/").filter(Boolean);
  // segments: [owner, model, "resolve", revision, ...file]
  if (segments.length < 4 || segments[2] !== "resolve") {return null;}
  const modelId = `${segments[0]}/${segments[1]}`;
  const file = segments.slice(4).join("/");
  return manifest.models[modelId]?.files[file] ?? null;
}

function isPinnedModelHost(url: string): boolean {
  try {
    const host = new URL(url).hostname;
    const allowed = new Set<string>();
    for (const raw of [manifest.remoteHost, getSelfHostUrl()]) {
      if (!raw) {continue;}
      try {
        allowed.add(new URL(raw).hostname);
      } catch (error) {
        // Ignore malformed optional configuration, but make the degraded
        // host allowlist observable without logging the raw value.
        logRateLimited(
          "warn",
          "model-integrity-configured-host",
          "Ignoring malformed configured model host",
          { error: error instanceof Error ? error.message : String(error) },
        );
      }
    }
    return allowed.has(host);
  } catch {
    return false;
  }
}

/**
 * Verify downloaded bytes against the pinned digest manifest.
 * Non-model URLs always return true (out of scope — bundle integrity covers
 * first-party assets). Returns false on digest mismatch; in production an
 * unpinned file from a pinned model host also returns false (fail-closed).
 */
export async function verifyModelBytes(
  url: string,
  bytes: ArrayBuffer | ArrayBufferView,
): Promise<boolean> {
  const digest = getPinnedDigest(url);
  if (digest === null) {
    if (import.meta.env.PROD && isPinnedModelHost(url)) {
      logger.error("[ModelIntegrity] Unpinned model file from pinned host", { url });
      return false;
    }
    return true;
  }
  const actual = await sha256Hex(bytes);
  if (actual !== digest) {
    logger.error("[ModelIntegrity] Digest mismatch", {
      url,
      expected: digest.slice(0, 16),
      actual: actual.slice(0, 16),
    });
    return false;
  }
  return true;
}

function toCacheKey(input: RequestInfo | URL): string {
  return typeof input === "string"
    ? input
    : input instanceof URL
      ? input.href
      : input.url;
}

function responseFromBytes(
  bytes: ArrayBuffer,
  original?: Response,
): Response {
  // Rebuild a MINIMAL header set. `response.clone().arrayBuffer()` returns
  // the DECODED bytes (fetch transparently decompresses Content-Encoding),
  // so preserving the original `Content-Encoding: gzip` / `Content-Length`
  // would make the browser try to inflate already-decoded bytes on match
  // → corrupted model files. Keep only content-type; recompute length.
  const headers = new Headers();
  const contentType = original?.headers.get("content-type");
  if (contentType) {headers.set("Content-Type", contentType);}
  headers.set("Content-Length", String(bytes.byteLength));
  return new Response(bytes, { status: 200, statusText: "OK", headers });
}

/**
 * Verifying cache in the shape transformers.js expects (`match`/`put`,
 * Web Cache API subset). `put` verifies bytes BEFORE storing and throws on
 * failure, which aborts the transformers.js model load (fail-closed).
 *
 * Backend: the browser CacheStorage (`bmf-model-integrity`) when available
 * (main thread + dedicated workers), falling back to an in-memory store in
 * environments without CacheStorage (jsdom, Node). Only verified bytes are
 * ever stored in either backend.
 */
export class VerifiedModelCache {
  private memory = new Map<string, { response: Response; size: number }>();
  private memoryBytes = 0;

  private async backend(): Promise<Cache | null> {
    if (typeof caches === "undefined") {return null;}
    try {
      return await caches.open(VERIFIED_CACHE_NAME);
    } catch (err) {
      logger.warn("[ModelIntegrity] CacheStorage unavailable; using memory", { error: err });
      return null;
    }
  }

  async match(input: RequestInfo | URL): Promise<Response | undefined> {
    const key = toCacheKey(input);
    const backend = await this.backend();
    if (backend) {
      return (await backend.match(key)) ?? undefined;
    }
    // Clone so successive matches each get a fresh body (the Web Cache API
    // returns a new Response per match; a shared instance would hand
    // transformers.js a consumed stream on the second hit).
    const hit = this.memory.get(key);
    return hit ? hit.response.clone() : undefined;
  }

  private async pruneBackend(backend: Cache, keepKey: string): Promise<void> {
    try {
      const requests = await backend.keys();
      if (requests.length <= MAX_MODEL_CACHE_ENTRIES) {
        let total = 0;
        for (const request of requests) {
          const response = await backend.match(request);
          total += Number(response?.headers.get("content-length")) || 0;
        }
        if (total <= MAX_MODEL_CACHE_BYTES) {return;}
      }

      // Cache.keys() is insertion ordered in browser implementations. Keep
      // the just-written entry and evict oldest entries until both bounds are
      // satisfied; model bytes are untrusted storage input, not a reason to
      // allow unbounded CacheStorage growth.
      let total = 0;
      const sizes: Array<{ request: Request; size: number }> = [];
      for (const request of requests) {
        const response = await backend.match(request);
        const size = Number(response?.headers.get("content-length")) || 0;
        sizes.push({ request, size });
        total += size;
      }
      let count = requests.length;
      for (const entry of sizes) {
        if (count <= MAX_MODEL_CACHE_ENTRIES && total <= MAX_MODEL_CACHE_BYTES) {break;}
        if (entry.request.url === keepKey) {continue;}
        if (await backend.delete(entry.request)) {
          count--;
          total -= entry.size;
        }
      }
    } catch (error) {
      logger.warn("[ModelIntegrity] Model-cache pruning failed", { error });
    }
  }

  private pruneMemory(keyToKeep: string): void {
    for (const [key, entry] of this.memory) {
      if (this.memory.size <= MAX_MODEL_CACHE_ENTRIES && this.memoryBytes <= MAX_MODEL_CACHE_BYTES) {break;}
      if (key === keyToKeep) {continue;}
      this.memory.delete(key);
      this.memoryBytes -= entry.size;
    }
  }

  async put(
    input: RequestInfo | URL,
    response: Response,
    _progress?: (data: { progress: number; loaded: number; total: number }) => void,
  ): Promise<void> {
    const key = toCacheKey(input);
    let bytes: ArrayBuffer;
    try {
      bytes = await response.clone().arrayBuffer();
    } catch (err) {
      throw new ModelIntegrityError(
        key,
        `could not read response body for verification: ${String(err)}`,
      );
    }
    if (!(await verifyModelBytes(key, bytes))) {
      throw new ModelIntegrityError(
        key,
        "bytes do not match the pinned SHA-256 digest (or unpinned file from pinned host)",
      );
    }
    const stored = responseFromBytes(bytes, response);
    const backend = await this.backend();
    if (backend) {
      await backend.put(key, stored);
      await this.pruneBackend(backend, key);
    } else {
      const size = bytes.byteLength;
      const previous = this.memory.get(key);
      if (previous) {this.memoryBytes -= previous.size;}
      this.memory.set(key, { response: stored, size });
      this.memoryBytes += size;
      this.pruneMemory(key);
    }
  }

  async delete(input: RequestInfo | URL): Promise<boolean> {
    const key = toCacheKey(input);
    const backend = await this.backend();
    if (backend) {
      return backend.delete(key);
    }
    const entry = this.memory.get(key);
    if (!entry) {return false;}
    this.memory.delete(key);
    this.memoryBytes -= entry.size;
    return true;
  }
}

export function createVerifiedModelCache(): VerifiedModelCache {
  return new VerifiedModelCache();
}

/**
 * Wire integrity into a transformers.js `env` object:
 *   - useCustomCache = true, customCache = verifying cache (all model
 *     downloads verified fail-closed)
 *   - remoteHost optionally redirected to a self-hosted mirror via
 *     VITE_MODEL_SELF_HOST_URL (digests are path-keyed, so any origin that
 *     serves the same bytes validates)
 *
 * The `env.fetch` hook is intentionally NOT overridden: routing model
 * downloads through the network firewall would require huggingface.co (or
 * the mirror) to be user-whitelisted, a behavioral regression. Origin policy
 * stays with CSP connect-src; byte integrity is enforced here.
 */
export function configureModelIntegrity(env: {
  useCustomCache?: boolean;
  customCache?: unknown;
  remoteHost?: string;
}): void {
  env.useCustomCache = true;
  env.customCache = createVerifiedModelCache();
  const selfHost = getSelfHostUrl();
  if (selfHost) {
    env.remoteHost = selfHost;
    logger.info("[ModelIntegrity] Model remoteHost redirected to self-hosted mirror", {
      host: selfHost,
    });
  } else {
    logger.info("[ModelIntegrity] Verified model cache installed");
  }
}


