import { writeFileSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, '..', 'privacy-translations.json');
const existing = JSON.parse(readFileSync(outPath, 'utf8'));

function mk(code, d) {
  const ps = [
    [d.s1t, d.s1x], [d.s2t, d.s2x, [d.s2i1]], [d.s3t, d.s3x, d.s3i],
    [d.s4t, d.s4x, d.s4i, d.s4x2, d.s4i2], [d.s5t, d.s5x, d.s5i, d.s5x2],
    [d.s6t, d.s6x, d.s6i, d.s6x2], [d.s7t, d.s7x, d.s7i], [d.s8t, d.s8x, d.s8i],
    [d.s9t, d.s9x, d.s9i, d.s9x2], [d.s10t, d.s10x, d.s10i],
    [d.s11t, d.s11x, d.s11i, d.s11x2], [d.s12t, d.s12x],
    [d.s13t, d.s13x, d.s13i, d.s13x2], [d.s14t, d.s14x], [d.s15t, d.s15x],
    [d.s16t, d.s16x], [d.s17t, d.s17x, [d.s17i1]]
  ].map(s => { const o = {}; if(s[0]) o.title=s[0]; if(s[1]) o.text=s[1]; if(s[2]) o.items=s[2]; if(s[3]) o.text2=s[3]; if(s[4]) o.items2=s[4]; return o; });
  const ts = [
    [d.t1t, d.t1x], [d.t2t, d.t2x, d.t2i], [d.t3t, d.t3x, d.t3i],
    [d.t4t, d.t4x, d.t4i], [d.t5t, d.t5x, d.t5i], [d.t6t, d.t6x, d.t6i],
    [d.t7t, null, d.t7i], [d.t8t, d.t8x], [d.t9t, d.t9x], [d.t10t, d.t10x, [d.t10i1]]
  ].map(s => { const o = {}; if(s[0]) o.title=s[0]; if(s[1]) o.text=s[1]; if(s[2]) o.items=s[2]; return o; });
  return { lang:code, title:d.title, metaDesc:d.metaDesc, lastUpdatedLabel:d.lastUpdatedLabel, lastUpdatedDate:d.lastUpdatedDate, termsLastUpdatedDate:d.termsLastUpdatedDate, privacyTitle:d.privacyTitle, privacySections:ps, termsTitle:d.termsTitle, termsSections:ts, footerCopyright:d.footerCopyright };
}

// ============ CS ============
existing['cs'] = mk('cs', {
  title: 'Zásady ochrany osobních údajů a podmínky služby',
  metaDesc: 'Zásady ochrany osobních údajů a podmínky služby BookmarkForge. Vaše data zůstávají na vašem zařízení. Local-first, šifrování, zero-knowledge.',
  lastUpdatedLabel: 'Poslední aktualizace', lastUpdatedDate: '9. září 2026', termsLastUpdatedDate: '23. července 2026',
  privacyTitle: 'Zásady ochrany osobních údajů',
  s1t:'Správce osobních údajů', s1x:'Správcem osobních údajů popsaných v těchto zásadách je BookmarkForge (kontakt v oddílu 17). Pro doplňkový server a licenční infrastrukturu jedná provozovatel daného nasazení jako správce.',
  s2t:'Úvod a rozsah', s2x:'BookmarkForge ("my", "náš" nebo "nás") se zavazuje chránit vaše soukromí. Tyto Zásady ochrany osobních údajů vysvětlují, jak zpracováváme vaše data při používání naší aplikace.', s2i1:'Klíčový princip: BookmarkForge běží ze 100 % lokálně na vašem zařízení. Vaše záložky, poznámky, dokumenty a konverzace s AI se ukládají v lokální databázi vašeho prohlížeče a nikdy se nepřenášejí na naše servery.',
  s3t:'Data, která NESBÍRÁME', s3x:'Chceme být jasní v tom, co NESBÍRÁME:', s3i:['Žádné záložky ani URL odesílané na naše servery','Žádné poznámky ani dokumenty, které opouštějí vaše zařízení','Žádné AI podněty ani odpovědi, které zaznamenáváme','Žádná historie prohlížení, která by byla sledována','Žádné osobní údaje vyžadované k používání aplikace','Žádná analytika shromažďovaná ve výchozím nastavení'],
  s4t:'Kde žijí vaše data', s4x:'Všechna vaše data se ukládají lokálně ve vašem prohlížeči prostřednictvím:', s4i:['IndexedDB – pro záložky, dokumenty a nastavení','Bezpečné úložiště – pro šifrované klíče a hesla','Mezipaměť Service Worker – pro offline provoz'], s4x2:'Vaše data nikdy neopustí vaše zařízení, pokud výslovně:', s4i2:['Neexportujete soubor zálohy','Nesdílíte svůj vault s jiným zařízením','Nepoužijete cloudového AI poskytovatele (vaše podněty jdou přímo k poskytovateli, ne přes nás)'],
  s5t:'Šifrování', s5x:'Vaše data jsou šifrována prostřednictvím:', s5i:['Šifrování AES-GCM-256 pro veškerý uložený obsah','Argon2id (KDF odolný vůči paměti) pro klíče odvozené z hesel','Klíče se odvozují a ukládají lokálně ve vašem prohlížeči'], s5x2:'Nemáme přístup k vašim šifrovacím klíčům ani heslům.',
  s6t:'CSP reporty (Content Security Policy)', s6x:'BookmarkForge používá CSP hlavičky k zabránění útokům cross-site scripting a injekci dat. Pokud váš prohlížeč zablokuje zdroj kvůli těmto hlavičkám, automaticky odešle stručný technický report o porušení na stejný server, který aplikaci obsluhuje (endpont /csp-report). Provozovatel uchovává pouze:', s6i:['Původ blokovaného zdroje (cesta, dotaz a fragment se odstraní; nikdy vaše osobní údaje)','Porušenou CSP direktivu','Původ stránky, kde k porušení došlo','SHA-256 hash vaší IP adresy, použitý pouze k omezení frekvence – vaše IP se nikdy neukládá'], s6x2:'Toto je standardní chování prohlížeče požadované specifikací CSP: prohlížeč tyto reporty odesílá automaticky, bez opt-in uživatele, protože jsou součástí bezpečnostního mechanismu. Nepřipojují se cookies, identifikátory ani historie prohlížení a nikdy se nezahrnuje obsah vaultu.',
  s7t:'AI poskytovatelé', s7x:'Při používání AI funkcí:', s7i:['Lokální AI (WebLLM): běží zcela ve vašem prohlížeči. Žádná data neopustí vaše zařízení.','Cloudová AI (Gemini, OpenAI, Anthropic atd.): vaše podněty se odesílají přímo poskytovateli. My je nezachytáváme, neukládáme ani nezaznamenáváme. Každý poskytovatel má své vlastní zásady ochrany soukromí.'],
  s8t:'Volitelné reporty chyb (pouze s opt-in)', s8x:'Můžete se rozhodnout aktivovat reportování chyb v Nastavení. Pokud jsou aktivovány:', s8i:['Přijímáme anonymní technické záznamy chyb při selhání aplikace','NIKDY NEPŘIJÍMÁME: vaše záložky, texty, URL, podněty ani žádný osobní obsah','Odesílají se pouze technické stack traces a informace o zařízení','Můžete to kdykoli deaktivovat'],
  s9t:'Bookmarklet PWA a sdílení', s9x:'BookmarkForge nabízí dva způsoby ukládání obsahu z prohlížeče:', s9i:['Bookmarklet: přetáhněte tlačítko "Uložit do Forge" do panelu záložek. Klikněte na něj na jakékoli stránce pro okamžité uložení.','PWA sdílení: na mobilním zařízení použijte nativní nabídku sdílení prohlížeče k odesílání odkazů do BookmarkForge.'], s9x2:'Oba způsoby odesílají pouze URL a název stránky do aplikace, když je výslovně aktivujete. Nedochází ke sledování aktivity prohlížení.',
  s10t:'Služby třetích stran', s10x:'Používáme následující služby třetích stran:', s10i:['Google Fonts – pro typografii (fonty se ukládají lokálně v mezipaměti)','AI poskytovatelé – Google, OpenAI, Anthropic atd. (pouze pokud je nakonfigurujete)'],
  s11t:'Vaše práva (GDPR)', s11x:'BookmarkForge je navržen tak, abychom NIKDY NEOBDRŽELI vaše osobní údaje, což znamená, že většina povinností GDPR mizí svým designem. Podle Obecného nařízení o ochraně osobních údajů (GDPR) si ponecháváte následující práva:', s11i:['Právo na přístup (čl. 15): všechna vaše data jsou na vašem zařízení. Použijte funkci exportu pro získání kompletního, strojově čitelného kopie kdykoli.','Právo na opravu (čl. 16): upravujte své záložky, poznámky a dokumenty přímo v aplikaci.','Právo na výmaz (čl. 17): použijte vestavěnou funkci smazání dat (Nastavení → Zóna nebezpečí / Nuclear Forget). Trvale smaže všechna lokální data včetně šifrovaných klíčů a dat obnovení. My neuchováváme žádnou kopii.','Právo na přenositelnost (čl. 20): exporty používají otevřené formáty (JSON, Markdown, HTML) použitelné v jiných aplikacích.','Právo vznést námitku a omezit zpracování (čl. 18/21): veškeré volitelné zpracování (cloudová AI, telemetrie, reporty chyb) je přísně opt-in a může být kdykoli deaktivováno v Nastavení.','Právo odvolat souhlas (čl. 7): deaktivace volitelných funkcí v Nastavení okamžitě odvolá souhlas a zastaví veškeré související zpracování.'], s11x2:'Pro uplatnění jakéhokoli práva vyžadujícího náš zásah (např. stížnost na zpracování na serveru) nás kontaktujte e-mailem v oddílu 17. Máte také právo podat stížnost u svého národního dozorového úřadu pro ochranu osobních údajů.',
  s12t:'Právní základ a rejstřík zpracování', s12x:'V souladu s čl. 6 GDPR dokumentujeme právní základ každé činnosti zpracování, která vede k vynesení dat z vašeho zařízení. Rejstřík zahrnuje: účely, kategorie subjektů, kategorie osobních údajů, příjemce, doby uchovávání a bezpečnostní opatření (šifrování AES-256-GCM na straně klienta, TLS 1.3 při přenosu, HMAC podepsaná signalizace, omezení frekvence). Veškerá ostatní data – vaše záložky, poznámky, dokumenty, hesla – se zpracovávají výhradně na vašem zařízení pod vaší kontrolou a tím pádem jsou mimo rozsah zpracování GDPR z naší strany.',
  s13t:'Subdodavatelé a mezinárodní přenosy', s13x:'Při používání volitelných funkcí mohou být data zpracována následujícími třetími stranami (subdodavatelé). Každý přenos probíhá pouze při výslovném použití funkce:', s13i:['Google (Gemini API) – cloudové AI podněty a generovaná média. Zpracovává data v Google Cloud. Přenosy mimo EHP mohou probíhat na základě standardních smluvních doložek Google.','OpenAI / Anthropic / Groq / OpenRouter / Hugging Face – alternativní cloudoví AI poskytovatelé, pouze pokud je nakonfigurujete.','Whop – platba Pro licence a ověření práva. Whop jedná jako nezávislý správce dat o platbě.','Sentry (Functional Software) – volitelné reporty chyb, pouze pokud je aktivujete. Sentry jedná jako zpracovatel na základě smlouvy o zpracování dat.'], s13x2:'Neprodáváme, nepůjčujeme ani nesdílíme vaše data pro reklamní účely. Nepoužíváme sledovací cookies ani analytické skripty třetích stran. Mezinárodní přenosy: když poskytovatel zpracovává data mimo EHP, přenosy se opírají o rozhodnutí o přiměřenosti nebo standardní smluvní doložky.',
  s14t:'Rejstřík činností zpracování (souhrn ROPA)', s14x:'Vede se souhrnný rejstřík činností zpracování (čl. 30 GDPR) zahrnující: účely, kategorie subjektů, kategorie osobních údajů, příjemce, doby uchovávání a bezpečnostní opatření.',
  s15t:'Ochrana soukromí nezletilých', s15x:'BookmarkForge není určen pro osoby mladší 13 let (nebo ekvivalentní minimální věk v vaší jurisdikci). Vědomě neshromažďujeme žádné osobní údaje od nikoho.',
  s16t:'Změny těchto zásad', s16x:'Tyto Zásady ochrany osobních údajů můžeme průběžně aktualizovat. Významné změny budou promítnuty v datu "Poslední aktualizace" výše a změny týkající se zpracování budou oznámeny v aplikaci před jejich účinností.',
  s17t:'Kontakt', s17x:'Pro dotazy týkající se ochrany soukromí, žádosti subjektů nebo obavy:', s17i1:'E-mail: bookmarkforge@proton.me',
  termsTitle:'Podmínky služby',
  t1t:'Přijetí podmínek', t1x:'Používáním BookmarkForge přijímáte tyto Podmínky služby. Pokud nesouhlasíte, nepoužívejte aplikaci.',
  t2t:'Popis služby', t2x:'BookmarkForge je local-first aplikace pro správu znalostí, která vám umožňuje:', t2i:['Ukládat a organizovat záložky','Vytvářet a upravovat dokumenty','Používat AI funkce (lokálně nebo prostřednictvím cloudových poskytovatelů)','Synchronizovat data mezi vašimi zařízeními prostřednictvím peer-to-peer připojení'],
  t3t:'Local-first povaha', t3x:'Chápete a souhlasíte s tím, že:', t3i:['BookmarkForge běží zcela ve vašem prohlížeči','Všechna data se ukládají lokálně na vašem zařízení','My nehostujeme, neukládáme ani nezálohujeme vaše data na našich serverech','Jste odpovědní za zálohování svých dat pomocí funkce exportu'],
  t4t:'Odpovědnosti uživatele', t4x:'Souhlasíte s tím, že:', t4i:['Budete udržovat zálohy důležitých dat','Budete chránit heslo svého vaultu (nemůžeme jej obnovit)','Budete používat aplikaci v souladu s platnými zákony','Nebudete používat aplikaci k nezákonným účelům'],
  t5t:'AI funkce', t5x:'Při používání AI funkcí:', t5i:['Jste odpovědní za obsah svých podnětů','Cloudoví AI poskytovatelé mají své vlastní podmínky služby a zásady ochrany soukromí','Negarantujeme přesnost obsahu generovaného AI','Lokální AI modely vyžadují kompatibilní hardware (podpora WebGPU)'],
  t6t:'Omezení odpovědnosti', t6x:'BookmarkForge je poskytován "tak jak je" bez jakýchkoli záruk. Neodpovídáme za:', t6i:['Ztrátu dat způsobenou vyčištěním mezipaměti prohlížeče','Selhání hardwaru','Nekompatibilitu s vaším zařízením','Chyby v obsahu generovaném AI'],
  t7t:'Duševní vlastnictví', t7i:['Kód a design BookmarkForge jsou chráněny autorským právem','Váš obsah (záložky, poznámky, dokumenty) zůstává váš','Nepožadujeme vlastnictví vašich dat'],
  t8t:'Ukončení', t8x:'Protože BookmarkForge běží lokálně, není žádný účet ke zrušení. Můžete kdykoli přestat používat aplikaci zavřením prohlížeče.',
  t9t:'Rozhodné právo', t9x:'Tyto podmínky se řídí platným právem. Jakékoli spory budou vyřešeny příslušnými soudy.',
  t10t:'Kontakt', t10x:'Pro dotazy týkající se těchto podmínek:', t10i1:'E-mail: bookmarkforge@proton.me',
  footerCopyright:'Všechna práva vyhrazena.'
});

// ============ DA ============
existing['da'] = mk('da', {
  title:'Privatlivspolitik og servicevilkår',
  metaDesc:'Privatlivspolitik og servicevilkår for BookmarkForge. Dine data forbliver på din enhed. Local-first, kryptering, zero-knowledge.',
  lastUpdatedLabel:'Senest opdateret', lastUpdatedDate:'9. september 2026', termsLastUpdatedDate:'23. juli 2026',
  privacyTitle:'Privatlivspolitik',
  s1t:'Dataansvarlig', s1x:'Den dataansvarlige for de data, der er beskrevet i denne politik, er BookmarkForge (kontakt i afsnit 17). For supplementserveren og licensinfrastrukturen fungerer operatøren af den pågældende implementering som dataansvarlig.',
  s2t:'Indledning og omfang', s2x:'BookmarkForge ("vi", "vores" eller "os") er forpligtet til at beskytte dit privatliv. Denne privatlivspolitik forklarer, hvordan vi behandler dine data, når du bruger vores applikation.', s2i1:'Nøgleprincippet: BookmarkForge kører 100 % lokalt på din enhed. Dine bogmærker, noter, dokumenter og AI-samtaler gemmes i din browsers lokale database og sendes aldrig til vores servere.',
  s3t:'Data vi IKKE indsamler', s3x:'Vi vil være klare om, hvad vi IKKE indsamler:', s3i:['Ingen bogmærker eller URL\'er sendt til vores servere','Ingen noter eller dokumenter, der forlader din enhed','Ingen AI-prompter eller svar, der registreres af os','Ingen browsinghistorik, der spores','Ingen personlige data, der kræves for at bruge applikationen','Ingen analytics, der indsamles som standard'],
  s4t:'Hvor dine data bor', s4x:'Alle dine data gemmes lokalt i din browser via:', s4i:['IndexedDB – til bogmærker, dokumenter og indstillinger','Sikker opbevaring – til krypterede nøgler og adgangskoder','Service Worker-cache – til offline-funktion'], s4x2:'Dine data forlader aldrig din enhed, medmindre du eksplicit:', s4i2:['Eksporterer en sikkerhedskopifil','Deler dit vault med en anden enhed','Bruger en cloud AI-udbyder (dine prompts går direkte til udbyderen, ikke gennem os)'],
  s5t:'Kryptering', s5x:'Dine data krypteres via:', s5i:['AES-GCM-256-kryptering til alt gemt indhold','Argon2id (hukommelsesresistent KDF) til nøgler afledt af adgangskoder','Nøglerne afledes og gemmes lokalt i din browser'], s5x2:'Vi har ikke adgang til dine krypteringsnøgler eller adgangskoder.',
  s6t:'CSP-rapporter (Content Security Policy)', s6x:'BookmarkForge bruger CSP-headere til at forhindre cross-site scripting-angreb og datainjektion. Hvis din browser blokerer en ressource på grund af disse headere, sender den automatisk en kort teknisk overtrædelsesrapport til den samme server, der betjener applikationen (endpoint /csp-report). Operatøren beholder kun:', s6i:['Oprindelsen af den blokerede ressource (stien, forespørgslen og fragmentet fjernes; aldrig dine personlige data)','Den overtrådte CSP-direktiv','Oprindelsen af siden, hvor overtrædelsen fandt sted','Et SHA-256-hash af din IP-adresse, brugt udelukkende til frekvensbegrænsning – din IP gemmes aldrig'], s6x2:'Dette er standard browseradfærd ifølge CSP-specifikationen: browseren sender disse rapporter automatisk, uden brugerens opt-in, da de er en del af den sikkerhedsbeskyttelse, der beskytter dig. Der vedhæftes ikke cookies, identifikatorer eller browsinghistorik, og indholdet fra vault inkluderes aldrig.',
  s7t:'AI-udbydere', s7x:'Når du bruger AI-funktioner:', s7i:['Lokal AI (WebLLM): kører udelukkende i din browser. Ingen data forlader din enhed.','Cloud AI (Gemini, OpenAI, Anthropic osv.): dine prompts sendes direkte til udbyderen. Vi opsamler, gemmer eller registrerer ikke disse anmodninger. Hver udbyder har sin egen privatlivspolitik.'],
  s8t:'Valgfrie fejlrapporter (kun med opt-in)', s8x:'Du kan vælge at aktivere fejlrapportering i Indstillinger. Hvis de aktiveres:', s8i:['Vi modtager anonyme tekniske fejllogs, når applikationen fejler','VI MODTAGER ALDRIG: dine bogmærker, tekster, URL\'er, prompts eller noget personligt indhold','Kun tekniske stack traces og enhedsinformation sendes','Du kan deaktivere det når som helst'],
  s9t:'Bookmarklet PWA og delingsdestination', s9x:'BookmarkForge tilbyder to måder at gemme indhold fra din browser på:', s9i:['Bookmarklet: træk knappen "Gem i Forge" til bogmærkelinjen. Klik på den på enhver side for øjeblikkelig gemning.','PWA delingsdestination: på mobilen, brug browserens native delingsmenu til at sende links til BookmarkForge.'], s9x2:'Begge metoder sender kun URL\'en og sidetitlen til applikationen, når du eksplicit aktiverer dem. Der spores ingen browsingaktivitet.',
  s10t:'Tredjepartstjenester', s10x:'Vi bruger følgende tredjepartstjenester:', s10i:['Google Fonts – til typografi (skrifttyper cache\'s lokalt)','AI-udbydere – Google, OpenAI, Anthropic osv. (kun hvis du konfigurerer dem)'],
  s11t:'Dine rettigheder (GDPR)', s11x:'BookmarkForge er designet, så vi ALDRIG modtager dine personlige data, hvilket betyder, at de fleste GDPR-forpligtelser forsvinder ved design. I henhold til Generel Forordning om Databeskyttelse (GDPR) bevarer du følgende rettigheder:', s11i:['Indsigtsret (art. 15): alle dine data er på din enhed. Brug eksportfunktionen til at få et komplet, maskinlæsbart kop i til enhver tid.','Ret til berigtigelse (art. 16): rediger dine bogmærker, noter og dokumenter direkte i applikationen.','Ret til sletning (art. 17): brug den indbyggede datasletningsfunktion (Indstillinger → Farezone / Nuclear Forget). Dette sletter permanent alle lokale data, inklusive krypterede nøgler og gendannelsesdata. Vi bevarer ingen kopi.','Ret til dataportabilitet (art. 20): eksporter bruger åbne formater (JSON, Markdown, HTML), der kan bruges i andre applikationer.','Ret til indsigelse og begrænsning af behandling (art. 18/21): al valgfri behandling (cloud AI, telemetri, fejlrapporter) er strengt opt-in og kan deaktiveres når som helst i Indstillinger.','Ret til at trække samtykke tilbage (art. 7): deaktivering af valgfrie funktioner i Indstillinger trækker samtykke tilbage øjeblikkeligt og stopper al relateret behandling.'], s11x2:'For at udøve nogen rettighed, der kræver vores indblanding (f.eks. en klage over behandling på serveren), kontakt os via e-mail i afsnit 17. Du har også ret til at indgive en klage til din nationale databeskyttelsesmyndighed.',
  s12t:'Lovgrundlag og behandlingsregister', s12x:'I henhold til art. 6 i GDPR dokumenterer vi det retsgrundlag for hver behandlingsaktivitet, der medfører, at data forlader din enhed. Registret omfatter: formål, datakategorier, datapersonkategorier, modtagere, opbevaringstider og sikkerhedsforanstaltninger (AES-256-GCM-kryptering på klientsiden, TLS 1.3 under transport, HMAC-signerede signaler, frekvensbegrænsning). Alle andre data – dine bogmærker, noter, dokumenter, adgangskoder – behandles udelukkende på din enhed under din kontrol og er derfor uden for GDPR-behandlingsomfanget fra vores side.',
  s13t:'Underleverandører og internationale overførsler', s13x:'Når du bruger valgfrie funktioner, kan data blive behandlet af følgende tredjeparter (underleverandører). Enhver overførsel sker kun, når du eksplicit bruger funktionen:', s13i:['Google (Gemini API) – cloud AI-prompter og genererede medier. Behandler data i Google Cloud. Overførsler uden for EØS kan ske under Googles standardkontraktbestemmelser.','OpenAI / Anthropic / Groq / OpenRouter / Hugging Face – alternative cloud AI-udbydere, kun hvis du konfigurerer dem.','Whop – Pro-licensbetaling og rettighedsverificering. Whop fungerer som uafhængig dataansvarlig for betalingsdata.','Sentry (Functional Software) – valgfrie fejlrapporter, kun hvis du aktiverer dem. Sentry fungerer som databehandlere under dataprocessoraftale.'], s13x2:'Vi sælger, udlejer eller deler ikke dine data til reklameformål. Vi bruger ikke sporingcookies eller analytics-skripter fra tredjeparter. Internationale overførsler: når en udbyder behandler data uden for EØS, baseres overførslerne på tilstrækkelighedsafgørelsen eller standardkontraktbestemmelser.',
  s14t:'Behandlingsaktivitetsregister (ROPA-sammenfatning)', s14x:'Der føres et sammenfattende register over behandlingsaktiviteter (art. 30 i GDPR), der omfatter: formål, datakategorier, datapersonkategorier, modtagere, opbevaringstider og sikkerhedsforanstaltninger.',
  s15t:'Beskyttelse af mindreårige', s15x:'BookmarkForge er ikke designet til personer under 13 år (eller den tilsvarende minimale alder i din jurisdiktion). Vi indsamler bevidst ingen personlige oplysninger fra nogen.',
  s16t:'Ændringer af denne politik', s16x:'Vi kan opdatere denne privatlivspolitik løbende. Vigtige ændringer vil blive afspejlet i datoen "Senest opdateret" ovenfor, og for ændringer, der påvirker behandlingen, vil blive annonceret i applikationen, inden de træder i kraft.',
  s17t:'Kontakt', s17x:'For spørgsmål vedrørende privatliv, forespørgsler fra registrerede eller bekymringer:', s17i1:'E-mail: bookmarkforge@proton.me',
  termsTitle:'Servicevilkår',
  t1t:'Accept af vilkår', t1x:'Ved at bruge BookmarkForge accepterer du disse servicevilkår. Hvis du ikke er enig, skal du ikke bruge applikationen.',
  t2t:'Beskrivelse af tjenesten', t2x:'BookmarkForge er en local-first videnhåndteringsapplikation, der giver dig mulighed for:', t2i:['Gemme og organisere bogmærker','Oprette og redigere dokumenter','Bruge AI-funktioner (lokalt eller via cloud-udbydere)','Synkronisere data mellem dine enheder via peer-to-peer-forbindelser'],
  t3t:'Local-first natur', t3x:'Du forstår og accepterer, at:', t3i:['BookmarkForge kører udelukkende i din browser','Alle data gemmes lokalt på din enhed','Vi værter, gemmer eller backer ikke dine data på vores servere','Du er ansvarlig for at tage backup af dine data med eksportfunktionen'],
  t4t:'Brugeransvar', t4x:'Du accepterer at:', t4i:['Vedligeholde sikkerhedskopier af vigtige data','Beskytte adgangskoden til dit vault (vi kan ikke gendanne den)','Bruge applikationen i overensstemmelse med gældende lovgivning','Ikke bruge applikationen til ulovlige formål'],
  t5t:'AI-funktioner', t5x:'Når du bruger AI-funktioner:', t5i:['Du er ansvarlig for indholdet af dine prompts','Cloud AI-udbydere har deres egne servicevilkår og privatlivspolitikker','Vi garanterer ikke nøjagtigheden af AI-genereret indhold','Lokale AI-modeller kræver kompatibelt hardware (WebGPU-understøttelse)'],
  t6t:'Ansvarsbegrænsning', t6x:'BookmarkForge leveres "som den er" uden garantier af nogen art. Vi er ikke ansvarlige for:', t6i:['Datatab som følge af browserens cache-cleanup','Hardwarefejl','Inkompatibilitet med din enhed','Fejl i AI-genereret indhold'],
  t7t:'Intellektuel ejendomsret', t7i:['Koden og designet af BookmarkForge er beskyttet af ophavsret','Dit indhold (bogmærker, noter, dokumenter) forbliver dit','Vi gør ikke krav på ejerskab af dine data'],
  t8t:'Opsigelse', t8x:'Da BookmarkForge kører lokalt, er der ingen konto at opsige. Du kan stoppe med at bruge applikationen når som helst ved at lukke din browser.',
  t9t:'Gældende lovgivning', t9x:'Disse vilkår er underlagt gældende lovgivning. Eventuelle tvister vil blive afgjort ved de kompetente domstole.',
  t10t:'Kontakt', t10x:'For spørgsmål om disse vilkår:', t10i1:'E-mail: bookmarkforge@proton.me',
  footerCopyright:'Alle rettigheder forbeholdes.'
});

writeFileSync(outPath, JSON.stringify(existing, null, 2), 'utf8');
console.log('Added cs, da. Total:', Object.keys(existing).length);
