import { writeFileSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, '..', 'privacy-translations.json');
const existing = JSON.parse(readFileSync(outPath, 'utf8'));

function mk(code, d) {
  const ps = [
    [d.s1t, d.s1x], [d.s2t, d.s2x, [d.s2i1]], [d.s3t, d.s3x, d.s3i],
    [d.s4t, d.s4x, d.s4i, d.s4x2, d.s4i2], [d.s5t, d.s5x, d.s5i, d.s5x2],
    [d.s6t, d.s6x, d.s6i, d.s6x2], [d.s7t, d.s7x, d.s7i], [d.s8t, d.s8x, d.s8i],
    [d.s9t, d.s9x, d.s9i, d.s9x2], [d.s10t, d.s10x, d.s10i],
    [d.s11t, d.s11x, d.s11i, d.s11x2], [d.s12t, d.s12x],
    [d.s13t, d.s13x, d.s13i, d.s13x2], [d.s14t, d.s14x], [d.s15t, d.s15x],
    [d.s16t, d.s16x], [d.s17t, d.s17x, [d.s17i1]]
  ].map(s => { const o={}; if(s[0]) o.title=s[0]; if(s[1]) o.text=s[1]; if(s[2]) o.items=s[2]; if(s[3]) o.text2=s[3]; if(s[4]) o.items2=s[4]; return o; });
  const ts = [
    [d.t1t, d.t1x], [d.t2t, d.t2x, d.t2i], [d.t3t, d.t3x, d.t3i],
    [d.t4t, d.t4x, d.t4i], [d.t5t, d.t5x, d.t5i], [d.t6t, d.t6x, d.t6i],
    [d.t7t, null, d.t7i], [d.t8t, d.t8x], [d.t9t, d.t9x], [d.t10t, d.t10x, [d.t10i1]]
  ].map(s => { const o={}; if(s[0]) o.title=s[0]; if(s[1]) o.text=s[1]; if(s[2]) o.items=s[2]; return o; });
  return { lang:code, title:d.title, metaDesc:d.metaDesc, lastUpdatedLabel:d.lastUpdatedLabel, lastUpdatedDate:d.lastUpdatedDate, termsLastUpdatedDate:d.termsLastUpdatedDate, privacyTitle:d.privacyTitle, privacySections:ps, termsTitle:d.termsTitle, termsSections:ts, footerCopyright:d.footerCopyright };
}

// ============ HI ============
existing['hi'] = mk('hi', {
  title:'गोपनीयता नीति और सेवा की शर्तें',
  metaDesc:'BookmarkForge की गोपनीयता नीति और सेवा की शर्तें। आपका डेटा आपके डिवाइस पर रहता है। लोकल-फ़र्स्ट, एन्क्रिप्शन, ज़ीरो-नॉलेज।',
  lastUpdatedLabel:'अंतिम अपडेट', lastUpdatedDate:'9 सितंबर 2026', termsLastUpdatedDate:'23 जुलाई 2026',
  privacyTitle:'गोपनीयता नीति',
  s1t:'डेटा नियंत्रक', s1x:'इस नीति में वर्णित डेटा का नियंत्रक BookmarkForge है (संपर्क अनुभाग 17 में)। पूरक सर्वर और लाइसेंस इन्फ्रास्ट्रक्चर के लिए, उस तैनाती के ऑपरेटर नियंत्रक के रूप में कार्य करता है।',
  s2t:'परिचय और दायरा', s2x:'BookmarkForge ("हम", "हमारा" या "हमें") आपकी गोपनीयता की रक्षा के लिए प्रतिबद्ध है। यह गोपनीयता नीति बताती है कि जब आप हमारा ऐप्लिकेशन उपयोग करते हैं तो हम आपके डेटा को कैसे संसाधित करते हैं।', s2i1:'मुख्य सिद्धांत: BookmarkForge 100% स्थानीय रूप से आपके डिवाइस पर चलता है। आपके बुकमार्क, नोट्स, दस्तावेज़ और AI बातचीत आपके ब्राउज़र के स्थानीय डेटाबेस में संग्रहीत होते हैं और कभी हमारे सर्वर पर नहीं भेजे जाते।',
  s3t:'हम कौन सा डेटा एकत्र नहीं करते', s3x:'हम स्पष्ट होना चाहते हैं कि हम क्या एकत्र नहीं करते:', s3i:['हमारे सर्वर पर भेजे गए कोई बुकमार्क या URL नहीं','आपके डिवाइस से बाहर जाने वाले कोई नोट्स या दस्तावेज़ नहीं','कोई AI प्रॉम्प्ट या उत्तर नहीं जो हम रिकॉर्ड करते हैं','कोई ब्राउज़िंग इतिहास नहीं जिसे ट्रैक किया जाता है','ऐप्लिकेशन उपयोग करने के लिए आवश्यक कोई व्यक्तिगत जानकारी नहीं','डिफ़ॉल्ट रूप से एकत्र कोई एनालिटिक्स नहीं'],
  s4t:'आपका डेटा कहाँ रहता है', s4x:'आपका सारा डेटा आपके ब्राउज़र में इनके माध्यम से स्थानीय रूप से संग्रहीत है:', s4i:['IndexedDB – बुकमार्क, दस्तावेज़ और सेटिंग्स के लिए','सुरक्षित स्टोरेज – एन्क्रिप्टेड कुंजी और पासवर्ड के लिए','Service Worker कैश – ऑफलाइन कार्यक्षमता के लिए'], s4x2:'आपका डेटा आपके डिवाइस से कभी बाहर नहीं जाता जब तक आप स्पष्ट रूप से:', s4i2:['बैकअप फ़ाइल एक्सपोर्ट करें','अपना वॉल्ट किसी अन्य डिवाइस के साथ साझा करें','क्लाउड AI प्रदाता का उपयोग करें (आपके प्रॉम्प्ट सीधे प्रदाता के पास जाते हैं, हमसे नहीं)'],
  s5t:'एन्क्रिप्शन', s5x:'आपका डेटा इनके माध्यम से एन्क्रिप्ट किया गया है:', s5i:['सभी संग्रहीत सामग्री के लिए AES-GCM-256 एन्क्रिप्शन','पासवर्ड से प्राप्त कुंजी के लिए Argon2id (मेमोरी-रेज़िस्टेंट KDF)','कुंजी आपके ब्राउज़र में स्थानीय रूप से व्युत्पन्न और संग्रहीत होती हैं'], s5x2:'हमारे पास आपकी एन्क्रिप्शन कुंजी या पासवर्ड तक पहुँच नहीं है।',
  s6t:'CSP रिपोर्ट (Content Security Policy)', s6x:'BookmarkForge क्रॉस-साइट स्क्रिप्टिंग और डेटा इंजेक्शन हमलों को रोकने के लिए CSP हेडर का उपयोग करता है। यदि आपका ब्राउज़र इन हेडर के कारण किसी स्रोत को ब्लॉक करता है, तो यह स्वचालित रूप से ऐप्लिकेशन को सेवा देने वाले सर्वर पर एक संक्षिप्त तकनीकी उल्लंघन रिपोर्ट भेजता है (/csp-report एंडपॉइंट)। ऑपरेटर केवल रखता है:', s6i:['अवरुद्ध स्रोत का मूल (पथ, क्वेरी और फ्रैगमेंट हटा दिया जाता है; कभी नहीं आपका व्यक्तिगत डेटा)','उल्लंघित CSP डायरेक्टिव','उस पेज का मूल जहाँ उल्लंघन हुआ','आपके IP पते का SHA-256 हैश, केवल फ्रीक्वेंसी लिमिटिंग के लिए उपयोग किया जाता है – आपका IP कभी संग्रहीत नहीं होता'], s6x2:'यह CSP स्पेसिफिकेशन द्वारा आवश्यक मानक ब्राउज़र व्यवहार है: ब्राउज़र इन रिपोर्ट को बिना उपयोगकर्ता के opt-in के स्वचालित रूप से भेजता है, क्योंकि ये उस सुरक्षा तंत्र का हिस्सा हैं जो आपकी रक्षा करता है। कुकीज़, पहचानकर्ता या ब्राउज़िंग इतिहास संलग्न नहीं होते, और वॉल्ट की सामग्री कभी शामिल नहीं होती।',
  s7t:'AI प्रदाता', s7x:'AI सुविधाओं का उपयोग करते समय:', s7i:['स्थानीय AI (WebLLM): पूरी तरह से आपके ब्राउज़र में चलता है। आपके डिवाइस से कोई डेटा बाहर नहीं जाता।','क्लाउड AI (Gemini, OpenAI, Anthropic आदि): आपके प्रॉम्प्ट सीधे प्रदाता को भेजे जाते हैं। हम इन अनुरोधों को इंटरसेप्ट, संग्रहीत या रिकॉर्ड नहीं करते। प्रत्येक प्रदाता की अपनी गोपनीयता नीति है।'],
  s8t:'वैकल्पिक त्रुटि रिपोर्ट (केवल opt-in)', s8x:'आप सेटिंग्स में त्रुटि रिपोर्टिंग सक्षम करने का विकल्प चुन सकते हैं। यदि सक्षम हो जाती हैं:', s8i:['हमें ऐप्लिकेशन के क्रैश होने पर अनाम तकनीकी त्रुटि लॉग प्राप्त होते हैं','हमें कभी नहीं मिलते: आपके बुकमार्क, टेक्स्ट, URL, प्रॉम्प्ट या कोई व्यक्तिगत सामग्री','केवल तकनीकी स्टैक ट्रेस और डिवाइस जानकारी भेजी जाती है','आप इसे कभी भी अक्षम कर सकते हैं'],
  s9t:'बुकमार्कलेट PWA और शेयरिंग डेस्टिनेशन', s9x:'BookmarkForge आपके ब्राउज़र से सामग्री सहेजने के दो तरीके प्रदान करता है:', s9i:['बुकमार्कलेट: "Forge में सहेजें" बटन को बुकमार्क बार में खींचें। तुरंत सहेजने के लिए किसी भी पेज पर क्लिक करें।','PWA शेयरिंग डेस्टिनेशन: मोबाइल पर, BookmarkForge को लिंक भेजने के लिए अपने ब्राउज़र के नेटिव शेयर मेनू का उपयोग करें।'], s9x2:'दोनों विधियाँ केवल URL और पेज शीर्षक ऐप्लिकेशन को भेजती हैं जब आप उन्हें स्पष्ट रूप से सक्षम करते हैं। कोई ब्राउज़िंग गतिविधि ट्रैक नहीं की जाती।',
  s10t:'तृतीय-पक्ष सेवाएँ', s10x:'हम निम्नलिखित तृतीय-पक्ष सेवाओं का उपयोग करते हैं:', s10i:['Google Fonts – टाइपोग्राफी के लिए (फ़ॉन्ट स्थानीय रूप से कैश होते हैं)','AI प्रदाता – Google, OpenAI, Anthropic आदि (केवल यदि आप उन्हें कॉन्फ़िगर करते हैं)'],
  s11t:'आपके अधिकार (GDPR)', s11x:'BookmarkForge इस तरह डिज़ाइन किया गया है कि हमें कभी आपका व्यक्तिगत डेटा न मिले, जिसका अर्थ है कि GDPR के अधिकांश दायित्व डिज़ाइन से गायब हो जाते हैं। सामान्य डेटा सुरक्षा विनियम (GDPR) के अनुसार, आपके पास निम्नलिखित अधिकार हैं:', s11i:['पहुँच का अधिकार (अनुच्छेद 15): आपका सारा डेटा आपके डिवाइस पर है। किसी भी समय पूर्ण, मशीन-पठनीय प्रतिलिपि प्राप्त करने के लिए एक्सपोर्ट फ़ंक्शन का उपयोग करें।','सुधार का अधिकार (अनुच्छेद 16): अपने बुकमार्क, नोट्स और दस्तावेज़ सीधे ऐप्लिकेशन में संपादित करें।','मिटाने का अधिकार (अनुच्छेद 17): एम्बेडेड डेटा डिलीशन फ़ंक्शन का उपयोग करें (सेटिंग्स → खतरा क्षेत्र / न्यूक्लियर फ़ॉरगेट)। यह सभी स्थानीय डेटा को स्थायी रूप से मिटा देता है, जिसमें एन्क्रिप्टेड कुंजी और रिकवरी डेटा शामिल हैं। हम कोई प्रतिलिपि नहीं रखते।','पोर्टेबिलिटी का अधिकार (अनुच्छेद 20): एक्सपोर्ट खुले प्रारूप (JSON, Markdown, HTML) का उपयोग करते हैं जो अन्य ऐप्लिकेशन में उपयोग किए जा सकते हैं।','आपत्ति और प्रसंस्करण सीमा का अधिकार (अनुच्छेद 18/21): सभी वैकल्पिक प्रसंस्करण (क्लाउड AI, टेलीमेट्री, त्रुटि रिपोर्ट) सख्त opt-in हैं और किसी भी समय सेटिंग्स में अक्षम किए जा सकते हैं।','सहमति वापस लेने का अधिकार (अनुच्छेद 7): सेटिंग्स में वैकल्पिक सुविधाओं को अक्षम करने से सहमति तुरंत वापस ले ली जाती है और सभी संबंधित प्रसंस्करण रुक जाता है।'], s11x2:'किसी भी अधिकार का प्रयोग करने के लिए जिसके लिए हमारे हस्तक्षेप की आवश्यकता है (जैसे सर्वर पर प्रसंस्करण के बारे में शिकायत), अनुभाग 17 में ईमेल द्वारा हमसे संपर्क करें। आपके पास अपनी राष्ट्रीय डेटा सुरक्षा प्राधिकरण के पास शिकायत दर्ज करने का भी अधिकार है।',
  s12t:'कानूनी आधार और प्रसंस्करण रजिस्टर', s12x:'GDPR के अनुच्छेद 6 के अनुसार, हम प्रत्येक प्रसंस्करण गतिविधि के कानूनी आधार को प्रलेखित करते हैं जिसके कारण आपके डिवाइस से डेटा बाहर जाता है। रजिस्टर में शामिल हैं: उद्देश्य, श्रेणियाँ, डेटा श्रेणियाँ, प्राप्तकर्ता, संरक्षण अवधि और सुरक्षा उपाय (AES-256-GCM एन्क्रिप्शन, TLS 1.3 ट्रांज़िट में, HMAC हस्ताक्षरित सिग्नलिंग, फ्रीक्वेंसी लिमिटिंग)। सभी अन्य डेटा – आपके बुकमार्क, नोट्स, दस्तावेज़, पासवर्ड – विशेष रूप से आपके डिवाइस पर आपके नियंत्रण में संसाधित होते हैं।',
  s13t:'उप-प्रसंस्करण और अंतर्राष्ट्रीय स्थानांतरण', s13x:'जब आप वैकल्पिक सुविधाओं का उपयोग करते हैं, तो डेटा निम्नलिखित तृतीय-पक्षों (उप-प्रसंस्करणकर्ताओं) द्वारा संसाधित किया जा सकता है। प्रत्येक स्थानांतरण तभी होता है जब आप स्पष्ट रूप से सुविधा का उपयोग करते हैं:', s13i:['Google (Gemini API) – क्लाउड AI प्रॉम्प्ट और जनरेटेड मीडिया। Google Cloud में डेटा संसाधित करता है। EU के बाहर स्थानांतरण Google के मानक संविदात्मक खंडों के तहत हो सकते हैं।','OpenAI / Anthropic / Groq / OpenRouter / Hugging Face – वैकल्पिक क्लाउड AI प्रदाता, केवल यदि आप उन्हें कॉन्फ़िगर करते हैं।','Whop – Pro लाइसेंस भुगतान और अधिकार सत्यापन। Whop भुगतान डेटा का स्वतंत्र नियंत्रक है।','Sentry (Functional Software) – वैकल्पिक त्रुटि रिपोर्ट, केवल यदि आप उन्हें सक्षम करते हैं। Sentry डेटा प्रसंस्करण समझौते के तहत प्रसंस्करणकर्ता है।'], s13x2:'हम आपका डेटा विज्ञापन उद्देश्यों के लिए नहीं बेचते, किराए पर नहीं देते या साझा नहीं करते। हम ट्रैकिंग कुकीज़ या तृतीय-पक्ष एनालिटिक्स स्क्रिप्ट का उपयोग नहीं करते। अंतर्राष्ट्रीय स्थानांतरण: जब कोई प्रदाता EU के बाहर डेटा संसाधित करता है, तो स्थानांतरण पर्याप्तता निर्णय या मानक संविदात्मक खंडों पर आधारित होते हैं।',
  s14t:'प्रसंस्करण गतिविधियों का रजिस्टर (ROPA सारांश)', s14x:'प्रसंस्करण गतिविधियों का एक सारांश रजिस्टर बनाए रखा जाता है (GDPR का अनुच्छेद 30) जिसमें शामिल हैं: उद्देश्य, श्रेणियाँ, डेटा श्रेणियाँ, प्राप्तकर्ता, संरक्षण अवधि और सुरक्षा उपाय।',
  s15t:'नाबालिगों की गोपनीयता', s15x:'BookmarkForge 13 वर्ष से कम आयु के व्यक्तियों के लिए डिज़ाइन नहीं किया गया है (या आपके अधिकार क्षेत्र में समकक्ष न्यूनतम आयु)। हम जानबूझकर किसी से भी व्यक्तिगत जानकारी एकत्र नहीं करते।',
  s16t:'इस नीति में परिवर्तन', s16x:'हम समय-समय पर इस गोपनीयता नीति को अपडेट कर सकते हैं। महत्वपूर्ण परिवर्तन ऊपर "अंतिम अपडेट" तिथि में परिलक्षित होंगे, और प्रसंस्करण को प्रभावित करने वाले परिवर्तन लागू होने से पहले ऐप्लिकेशन के अंदर घोषित किए जाएंगे।',
  s17t:'संपर्क', s17x:'गोपनीयता, डेटा विषय अनुरोधों या चिंताओं के बारे में प्रश्न:', s17i1:'ईमेल: bookmarkforge@proton.me',
  termsTitle:'सेवा की शर्तें',
  t1t:'शर्तों की स्वीकृति', t1x:'BookmarkForge का उपयोग करके, आप इन सेवा की शर्तों को स्वीकार करते हैं। यदि आप सहमत नहीं हैं, तो ऐप्लिकेशन का उपयोग न करें।',
  t2t:'सेवा का विवरण', t2x:'BookmarkForge एक लोकल-फ़र्स्ट ज्ञान प्रबंधन ऐप्लिकेशन है जो आपको अनुमति देता है:', t2i:['बुकमार्क सहेजें और व्यवस्थित करें','दस्तावेज़ बनाएं और संपादित करें','AI सुविधाओं का उपयोग करें (स्थानीय या क्लाउड प्रदाताओं के माध्यम से)','peer-to-peer कनेक्शन के माध्यम से अपने डिवाइस के बीच डेटा सिंक करें'],
  t3t:'लोकल-फ़र्स्ट प्रकृति', t3x:'आप समझते हैं और सहमत हैं कि:', t3i:['BookmarkForge पूरी तरह से आपके ब्राउज़र में चलता है','सभी डेटा आपके डिवाइस पर स्थानीय रूप से संग्रहीत है','हम आपके डेटा को अपने सर्वर पर होस्ट, संग्रहीत या बैकअप नहीं लेते','एक्सपोर्ट फ़ंक्शन के साथ अपने डेटा का बैकअप लेना आपकी जिम्मेदारी है'],
  t4t:'उपयोगकर्ता की जिम्मेदारियाँ', t4x:'आप सहमत हैं कि:', t4i:['अपने महत्वपूर्ण डेटा के बैकअप बनाए रखें','अपने वॉल्ट के पासवर्ड को सुरक्षित रखें (हम इसे पुनर्प्राप्त नहीं कर सकते)','लागू कानूनों के अनुसार ऐप्लिकेशन का उपयोग करें','गैरकानूनी उद्देश्यों के लिए ऐप्लिकेशन का उपयोग न करें'],
  t5t:'AI सुविधाएँ', t5x:'AI सुविधाओं का उपयोग करते समय:', t5i:['आप अपने प्रॉम्प्ट की सामग्री के लिए जिम्मेदार हैं','क्लाउड AI प्रदाताओं की अपनी सेवा की शर्तें और गोपनीयता नीतियाँ हैं','हम AI-जनरेटेड सामग्री की सटीकता की गारंटी नहीं देते','स्थानीय AI मॉडल के लिए संगत हार्डवेयर आवश्यक है (WebGPU समर्थन)'],
  t6t:'दायित्व की सीमा', t6x:'BookmarkForge "जैसा है" वैसा प्रदान किया जाता है किसी भी प्रकार की वारंटी के बिना। हम इनके लिए जिम्मेदार नहीं हैं:', t6i:['ब्राउज़र कैश क्लीनअप के कारण डेटा हानि','हार्डवेयर विफलताएँ','आपके डिवाइस के साथ असंगतता','AI-जनरेटेड सामग्री में त्रुटियाँ'],
  t7t:'बौद्धिक संपदा', t7i:['BookmarkForge का कोड और डिज़ाइन कॉपीराइट द्वारा सुरक्षित है','आपकी सामग्री (बुकमार्क, नोट्स, दस्तावेज़) आपकी ही रहती है','हम आपके डेटा पर स्वामित्व का दावा नहीं करते'],
  t8t:'समाप्ति', t8x:'चूंकि BookmarkForge स्थानीय रूप से चलता है, रद्द करने के लिए कोई खाता नहीं है। आप कभी भी अपना ब्राउज़र बंद करके ऐप्लिकेशन का उपयोग बंद कर सकते हैं।',
  t9t:'लागू कानून', t9x:'ये शर्तें लागू कानून के अधीन हैं। कोई भी विवाद सक्षम न्यायालयों में हल किया जाएगा।',
  t10t:'संपर्क', t10x:'इन शर्तों के बारे में प्रश्न:', t10i1:'ईमेल: bookmarkforge@proton.me',
  footerCopyright:'सर्वाधिकार सुरक्षित।'
});

// ============ HR ============
existing['hr'] = mk('hr', {
  title:'Pravila privatnosti i Uslužni uvjeti',
  metaDesc:'Pravila privatnosti i Uslužni uvjeti za BookmarkForge. Vaši podaci ostaju na vašem uređaju. Local-first, šifriranje, zero-knowledge.',
  lastUpdatedLabel:'Zadnje ažuriranje', lastUpdatedDate:'9. rujna 2026.', termsLastUpdatedDate:'23. srpnja 2026.',
  privacyTitle:'Pravila privatnosti',
  s1t:'Voditelj obrade', s1x:'Voditelj obrade podataka opisanih u ovim pravilima je BookmarkForge (za kontakt pogledajte odjeljak 17). Za dodatni poslužitelj i licencnu infrastrukturu, operater tog raspoređivanja djeluje kao voditelj.',
  s2t:'Uvod i opseg', s2x:'BookmarkForge ("mi", "naš" ili "nas") predan je zaštiti vaše privatnosti. Ova Pravila privatnosti objašnjavaju kako obrađujemo vaše podatke kada koristite našu aplikaciju.', s2i1:'Ključno načelo: BookmarkForge radi 100% lokalno na vašem uređaju. Vaše oznake, bilješke, dokumenti i AI razgovori pohranjeni su u lokalnoj bazi podataka vašeg preglednika i nikad se ne prenose na naše poslužitelje.',
  s3t:'Podaci koje NE prikupljamo', s3x:'Želimo biti jasni u vezi onoga što NE prikupljamo:', s3i:['Nema oznaka ili URL-ova poslanih na naše poslužitelje','Nema bilježaka ili dokumenata koji napuštaju vaš uređaj','Nema AI upita ili odgovora koje bilježimo','Nema povijesti pregledavanja koja se prati','Nema osobnih podataka potrebnih za korištenje aplikacije','Nema analitike koja se prikuplja prema zadanim postavkama'],
  s4t:'Gdje žive vaši podaci', s4x:'Svi vaši podaci pohranjeni su lokalno u vašem pregledniku putem:', s4i:['IndexedDB – za oznake, dokumente i postavke','Sigurna pohrana – za šifrirane ključeve i lozinke','Service Worker memorija – za rad izvan mreže'], s4x2:'Vaši podaci nikad ne napuštaju vaš uređaj osim ako eksplicitno:', s4i2:['Izvezete datoteku sigurnosne kopije','Podijelite svoj vault s drugim uređajem','Koristite cloud AI pružatelja (vaši upiti idu izravno pružatelju, ne kroz nas)'],
  s5t:'Šifriranje', s5x:'Vaši podaci šifrirani su putem:', s5i:['AES-GCM-256 šifriranje za sav pohranjeni sadržaj','Argon2id (KDF otporan na memoriju) za ključeve izvedene iz lozinki','Ključevi se izvode i pohranjuju lokalno u vašem pregledniku'], s5x2:'Nemamo pristup vašim ključevima za šifriranje niti lozinkama.',
  s6t:'CSP izvještaji (Content Security Policy)', s6x:'BookmarkForge koristi CSP zaglavlja za sprječavanje cross-site scripting napada i injekcije podataka. Ako vaš preglednik blokira resurs zbog ovih zaglavlja, automatski šalje kratki tehnički izvještaj o kršenju na isti poslužitelj koji služi aplikaciji (krajnja točka /csp-report). Operater čuva samo:', s6i:['Izvor blokiranog resursa (staza, upit i fragment se uklanjaju; nikad vaši osobni podaci)','Povrijeđenu CSP direktivu','Izvor stranice gdje se dogodilo kršenje','SHA-256 hash vaše IP adrese, korišten isključivo za ograničenje učestalosti – vaša IP se nikad ne pohranjuje'], s6x2:'Ovo je standardno ponašanje preglednika propisano CSP specifikacijom: preglednik šalje ove izvještaje automatski, bez opt-in korisnika, jer su dio sigurnosnog mehanizma koji vas štiti. Ne prilažu se kolačići, identifikatori niti povijest pregledavanja, a sadržaj vaulta nikad se ne uključuje.',
  s7t:'AI pružatelji', s7x:'Kada koristite AI funkcije:', s7i:['Lokalni AI (WebLLM): radi u potpunosti u vašem pregledniku. Nijedan podatak ne napušta vaš uređaj.','Cloud AI (Gemini, OpenAI, Anthropic itd.): vaši upiti se šalju izravno pružatelju. Mi ne presrećemo, pohranjujemo niti bilježimo te zahtjeve. Svaki pružatelj ima vlastitu politiku privatnosti.'],
  s8t:'Opcionalni izvještaji o greškama (samo s opt-in)', s8x:'Možete odabrati aktiviranje izvještavanja o greškama u Postavkama. Ako se aktiviraju:', s8i:['Primamo anonimne tehničke zapise grešaka kada aplikacija padne','NIKAD NE PRIMAMO: vaše oznake, tekstove, URL-ove, upite niti bilo koji osobni sadržaj','Šalju se samo tehnički stack traces i informacije o uređaju','Možete to deaktivirati u bilo kojem trenutku'],
  s9t:'Bookmarklet PWA i odredište za dijeljenje', s9x:'BookmarkForge nudi dva načina za pohranu sadržaja iz vašeg preglednika:', s9i:['Bookmarklet: povucite gumb "Spremi u Forge" u traku oznaka. Kliknite na njega na bilo kojoj stranici za trenutno spremanje.','PWA odredište za dijeljenje: na mobilnom uređaju koristite izbornik za dijeljenje vašeg preglednika za slanje veza u BookmarkForge.'], s9x2:'Oba načina šalju samo URL i naslov stranice aplikaciji kada ih eksplicitno aktivirate. Ne prati se nikakva aktivnost pregledavanja.',
  s10t:'Usluge trećih strana', s10x:'Koristimo sljedeće usluge trećih strana:', s10i:['Google Fonts – za tipografiju (fontovi se memoriraju lokalno)','AI pružatelji – Google, OpenAI, Anthropic itd. (samo ako ih konfigurirate)'],
  s11t:'Vaša prava (GDPR)', s11x:'BookmarkForge je dizajniran tako da NIKAD NE PRIMAMO vaše osobne podatke, što znači da većina GDPR obveza nestaje po dizajnu. Prema Općoj uredbi o zaštiti podataka (GDPR) zadržavate sljedeća prava:', s11i:['Pravo na pristup (čl. 15): svi vaši podaci su na vašem uređaju. Koristite funkciju izvoza za dobivanje potpunog, strojno čitljivog primjerka u bilo kojem trenutku.','Pravo na ispravak (čl. 16): uređujte svoje oznake, bilješke i dokumente izravno u aplikaciji.','Pravo na brisanje (čl. 17): koristite ugrađenu funkciju brisanja podataka (Postavke → Zona opasnosti / Nuclear Forget). Ovo trajno briše sve lokalne podatke, uključujući šifrirane ključeve i podatke za oporavak. Mi ne čuvamo nikakvu kopiju.','Pravo na prenosivost (čl. 20): izvozi koriste otvorene formate (JSON, Markdown, HTML) koji se mogu koristiti u drugim aplikacijama.','Pravo na prigovor i ograničenje obrade (čl. 18/21): sva opcionalna obrada (cloud AI, telemetrija, izvještaji o greškama) strogo je opt-in i može se deaktivirati u bilo kojem trenutku u Postavkama.','Pravo na povlačenje pristanka (čl. 7): deaktivacija opcionalnih značajki u Postavkama odmah povlači pristanak i zaustavlja svu povezanu obradu.'], s11x2:'Za ostvarivanje bilo kojeg prava koje zahtijeva našu intervenciju (npr. pritužbu na obradu na poslužitelju), kontaktirajte nas e-poštom u odjeljku 17. Također imate pravo podnijeti pritužbu svom nacionalnom tijelu za zaštitu podataka.',
  s12t:'Pravna osnova i registar obrade', s12x:'U skladu s čl. 6 GDPR-a dokumentiramo pravnu osnovu svake aktivnosti obrade koja dovodi do izlaska podataka s vašeg uređaja. Registar uključuje: svrhe, kategorije, kategorije osobnih podataka, primatelje, rokove čuvanja i sigurnosne mjere (AES-256-GCM šifriranje na strani klijenta, TLS 1.3 u prijenosu, HMAC potpisana signalizacija, ograničenje učestalosti). Svi ostali podaci – vaše oznake, bilješke, dokumenti, lozinke – obrađuju se isključivo na vašem uređaju pod vašom kontrolom.',
  s13t:'Podizvođači i međunarodni prijenosi', s13x:'Kada koristite opcionalne značajke, podaci mogu biti obrađeni od sljedećih trećih strana (podizvođači). Svaki prijenos se događa samo kada eksplicitno koristite značajku:', s13i:['Google (Gemini API) – cloud AI upiti i generirani mediji. Obrađuje podatke u Google Cloudu. Prijenosi izvan EGP-a mogu se dogoditi prema Google-ovim standardnim ugovornim klauzulama.','OpenAI / Anthropic / Groq / OpenRouter / Hugging Face – alternativni cloud AI pružatelji, samo ako ih konfigurirate.','Whop – plaćanje Pro licence i provjera prava. Whop djeluje kao neovisni voditelj podataka o plaćanju.','Sentry (Functional Software) – opcionalni izvještaji o greškama, samo ako ih aktivirate. Sentry djeluje kao obraditelj temeljem ugovora o obradi podataka.'], s13x2:'Ne prodajemo, ne iznajmljujemo niti dijelimo vaše podatke u reklamne svrhe. Ne koristimo kolačiće za praćenje niti skripte za analitiku trećih strana. Međunarodni prijenosi: kada pružatelj obrađuje podatke izvan EGP-a, prijenosi se temelje na odluci o adekvatnosti ili standardnim ugovornim klauzulama.',
  s14t:'Registar aktivnosti obrade (ROPA sažetak)', s14x:'Vodi se sažeti registar aktivnosti obrade (čl. 30 GDPR-a) koji obuhvaća: svrhe, kategorije, kategorije osobnih podataka, primatelje, rokove čuvanja i sigurnosne mjere.',
  s15t:'Privatnost maloljetnika', s15x:'BookmarkForge nije dizajniran za osobe mlađe od 13 godina (ili ekvivalentnu minimalnu dob u vašoj jurisdikciji). Svjesno ne prikupljamo osobne podatke od nikoga.',
  s16t:'Promjene ovih pravila', s16x:'Možemo povremeno ažurirati ova Pravila privatnosti. Značajne promjene bit će odražene u datumu "Zadnje ažuriranje" gore, a promjene koje utječu na obradu bit će objavljene unutar aplikacije prije stupanja na snagu.',
  s17t:'Kontakt', s17x:'Za pitanja o privatnosti, zahtjeve ispitanika ili zabrinutosti:', s17i1:'E-pošta: bookmarkforge@proton.me',
  termsTitle:'Uslužni uvjeti',
  t1t:'Prihvaćanje uvjeta', t1x:'Korištenjem BookmarkForge prihvaćate ove Uslužne uvjete. Ako se ne slažete, ne koristite aplikaciju.',
  t2t:'Opis usluge', t2x:'BookmarkForge je local-first aplikacija za upravljanje znanjem koja vam omogućuje:', t2i:['Pohranjivanje i organiziranje oznaka','Stvaranje i uređivanje dokumenata','Korištenje AI značajki (lokalno ili putem cloud pružatelja)','Sinkronizaciju podataka između vaših uređaja putem peer-to-peer veza'],
  t3t:'Local-first priroda', t3x:'Razumijete i slažete se da:', t3i:['BookmarkForge radi u potpunosti u vašem pregledniku','Svi podaci se pohranjuju lokalno na vašem uređaju','Mi ne hostamo, pohranjujemo niti backup-iramo vaše podatke na svojim poslužiteljima','Odgovorni ste za backup svojih podataka pomoću funkcije izvoza'],
  t4t:'Odgovornosti korisnika', t4x:'Slažete se da ćete:', t4i:['Održavati sigurnosne kopije svojih važnih podataka','Čuvati lozinku svog vaulta (ne možemo je oporaviti)','Koristiti aplikaciju u skladu sa zakonima','Ne koristiti aplikaciju u nezakonite svrhe'],
  t5t:'AI značajke', t5x:'Kada koristite AI značajke:', t5i:['Odgovorni ste za sadržaj svojih upita','Cloud AI pružatelji imaju vlastite uvjete usluge i politike privatnosti','Ne jamčimo točnost AI-generiranog sadržaja','Lokalni AI modeli zahtijevaju kompatibilan hardver (WebGPU podrška)'],
  t6t:'Ograničenje odgovornosti', t6x:'BookmarkForge se pruža "kakav jest" bez ikakvih jamstava. Nismo odgovorni za:', t6i:['Gubitak podataka zbog čišćenja memorije preglednika','Kvarove hardvera','Nespojivost s vašim uređajem','Greške u AI-generiranom sadržaju'],
  t7t:'Intelektualno vlasništvo', t7i:['Kod i dizajn BookmarkForge zaštićeni su autorskim pravom','Vaš sadržaj (oznake, bilješke, dokumenti) ostaje vaš','Ne polažemo pravo na vlasništvo vaših podataka'],
  t8t:'Otkazivanje', t8x:'Budući da BookmarkForge radi lokalno, nema računa za otkazivanje. Možete prestati koristiti aplikaciju u bilo kojem trenutku zatvaranjem preglednika.',
  t9t:'Mjerodavno pravo', t9x:'Ovi uvjeti podliježu mjerodavnom pravu. Svi sporovi rješit će se pred nadležnim sudovima.',
  t10t:'Kontakt', t10x:'Za pitanja o ovim uvjetima:', t10i1:'E-pošta: bookmarkforge@proton.me',
  footerCopyright:'Sva prava pridržana.'
});

writeFileSync(outPath, JSON.stringify(existing, null, 2), 'utf8');
console.log('Added hi, hr. Total:', Object.keys(existing).length);
