import { writeFileSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, '..', 'privacy-translations.json');
const existing = JSON.parse(readFileSync(outPath, 'utf8'));

function mk(code, d) {
  const ps = [
    [d.s1t, d.s1x], [d.s2t, d.s2x, [d.s2i1]], [d.s3t, d.s3x, d.s3i],
    [d.s4t, d.s4x, d.s4i, d.s4x2, d.s4i2], [d.s5t, d.s5x, d.s5i, d.s5x2],
    [d.s6t, d.s6x, d.s6i, d.s6x2], [d.s7t, d.s7x, d.s7i], [d.s8t, d.s8x, d.s8i],
    [d.s9t, d.s9x, d.s9i, d.s9x2], [d.s10t, d.s10x, d.s10i],
    [d.s11t, d.s11x, d.s11i, d.s11x2], [d.s12t, d.s12x],
    [d.s13t, d.s13x, d.s13i, d.s13x2], [d.s14t, d.s14x], [d.s15t, d.s15x],
    [d.s16t, d.s16x], [d.s17t, d.s17x, [d.s17i1]]
  ].map(s => { const o={}; if(s[0]) o.title=s[0]; if(s[1]) o.text=s[1]; if(s[2]) o.items=s[2]; if(s[3]) o.text2=s[3]; if(s[4]) o.items2=s[4]; return o; });
  const ts = [
    [d.t1t, d.t1x], [d.t2t, d.t2x, d.t2i], [d.t3t, d.t3x, d.t3i],
    [d.t4t, d.t4x, d.t4i], [d.t5t, d.t5x, d.t5i], [d.t6t, d.t6x, d.t6i],
    [d.t7t, null, d.t7i], [d.t8t, d.t8x], [d.t9t, d.t9x], [d.t10t, d.t10x, [d.t10i1]]
  ].map(s => { const o={}; if(s[0]) o.title=s[0]; if(s[1]) o.text=s[1]; if(s[2]) o.items=s[2]; return o; });
  return { lang:code, title:d.title, metaDesc:d.metaDesc, lastUpdatedLabel:d.lastUpdatedLabel, lastUpdatedDate:d.lastUpdatedDate, termsLastUpdatedDate:d.termsLastUpdatedDate, privacyTitle:d.privacyTitle, privacySections:ps, termsTitle:d.termsTitle, termsSections:ts, footerCopyright:d.footerCopyright };
}

// ============ FI ============
existing['fi'] = mk('fi', {
  title:'Tietosuojakäytäntö ja palveluehdot',
  metaDesc:'BookmarkForgen tietosuojakäytäntö ja palveluehdot. Tietosi pysyvät laitteellasi. Paikallinen ensin, salaus, zero-knowledge.',
  lastUpdatedLabel:'Viimeksi päivitetty', lastUpdatedDate:'9. syyskuuta 2026', termsLastUpdatedDate:'23. heinäkuuta 2026',
  privacyTitle:'Tietosuojakäytäntö',
  s1t:'Rekisterinpitäjä', s1x:'Tässä käytännössä kuvattujen tietojen rekisterinpitäjä on BookmarkForge (yhteystiedot kohdassa 17). Täydentävän palvelimen ja lisenssi-infrastruktuurin osalta kyseisen toteutuksen ylläpitäjä toimii rekisterinpitäjänä.',
  s2t:'Johdanto ja soveltamisala', s2x:'BookmarkForge ("me", "meidän" tai "meidät") on sitoutunut suojaamaan yksityisyyttäsi. Tämä tietosuojakäytäntö selittää, miten käsittelemme tietojasi käyttäessäsi sovellustamme.', s2i1:'Avainperiaate: BookmarkForge toimii 100 % paikallisesti laitteellasi. Kirjanmerkkisi, muistiinpanosi, dokumenttisi ja KI-keskustelusi tallennetaan selaimesi paikalliseen tietokantaan, eikä niitä koskaan siirretä palvelimillemme.',
  s3t:'Tiedot, joita EMME kerää', s3x:'Haluamme olla selkeitä sen suhteen, mitä EMME kerää:', s3i:['Ei kirjanmerkkejä tai URL-osoitteita lähetetä palvelimillemme','Ei muistiinpanoja tai dokumentteja, jotka poistuvat laitteeltasi','Ei KI-prompteja tai vastauksia, joita tallennamme','Ei selaushistoriaa, jota seurataan','Ei henkilökohtaisia tietoja, joita vaaditaan sovelluksen käyttöön','Ei analytiikkaa, jota kerätään oletuksena'],
  s4t:'Missä tietosi asuvat', s4x:'Kaikki tietosi tallennetaan paikallisesti selaimeen seuraavasti:', s4i:['IndexedDB – kirjanmerkkeihin, dokumentteihin ja asetuksiin','Turvallinen tallennustila – salattuihin avaimiin ja salasanoihin','Service Worker -välimuisti – offline-toiminnallisuuteen'], s4x2:'Tietosi eivät koskaan poistu laitteeltasi paitsi jos eksplisiittisesti:', s4i2:['Viennät varmuuskopiotiedoston','Jaat vaultisi toisen laitteen kanssa','Käytät pilvi-KI-palveluntarjoajaa (promptisi menevät suoraan palveluntarjoajalle, ei meidän kautta)'],
  s5t:'Salaus', s5x:'Tietosi salataan seuraavasti:', s5i:['AES-GCM-256 -salaus kaikelle tallennetulle sisällölle','Argon2id (muistinkestävä KDF) salasanoista johdetuille avaimille','Avaimet johdetaan ja tallennetaan paikallisesti selaimeen'], s5x2:'Meillä ei ole pääsyä salausavaimiisi tai salasanasi.',
  s6t:'CSP-raportit (Content Security Policy)', s6x:'BookmarkForge käyttää CSP-otsikkoja estääkseen cross-site scripting -hyökkäyksiä ja tietojen injektiota. Jos selaimesi estää resurssin näiden otsikoiden vuoksi, se lähettää automaattisesti lyhyen teknisen rikkomusraportin samalle palvelimelle, joka palvelee sovellusta (päätepiste /csp-report). Ylläpitäjä säilyttää vain:', s6i:['Estetyn resurssin lähteen (polku, kysely ja fragmentti poistetaan; koskaan henkilökohtaisia tietojasi)','Rikottu CSP-direktiivi','Sivun lähteen, jossa rikkomus tapahtui','SHA-256 -tiiviste IP-osoitteestasi, käytetty yksinomaan taajuusrajoitukseen – IP-osoitettasi ei koskaan tallenneta'], s6x2:'Tämä on selaimen standardikäyttäytyminen CSP-spesifikaation mukaan: selain lähettää nämä raportit automaattisesti ilman käyttäjän opt-in:ia, koska ne ovat osa sinua suojaavaa turvallisuusmekanismia. Liitteitä ei ole evästeitä, tunnisteita tai selaushistoriaa, eikä vaultin sisältöä koskaan sisällytetä.',
  s7t:'KI-palveluntarjoajat', s7x:'Käyttäessäsi KI-toimintoja:', s7i:['Paikallinen KI (WebLLM): toimii kokonaan selaimesi. Mikään tieto ei poistu laitteeltasi.','Pilvi-KI (Gemini, OpenAI, Anthropic jne.): promptisi lähetetään suoraan palveluntarjoajalle. Me emme sieppaa, tallenna tai kirjaa näitä pyyntöjä. Jokaisella palveluntarjoajalla on oma tietosuojakäytäntönsä.'],
  s8t:'Valinnaiset virheraportit (vain opt-in:illa)', s8x:'Voit päättää ottaa käyttöön virheraportoinnin Asetuksissa. Jos ne otetaan käyttöön:', s8i:['Saanme anonyymejä teknisiä virhelokeja sovelluksen kaatuessa','EMME KOSKAAN SAA: kirjanmerkkejäsi, tekstejä, URL-osoitteita, prompteja tai mitään henkilökohtaisaa sisältöä','Lähetetään vain teknisiä stack traceja ja laitetietoja','Voit poistaa sen käytöstä milloin tahansa'],
  s9t:'Bookmarklet PWA ja jakamiskohde', s9x:'BookmarkForge tarjoaa kaksi tapaa tallentaa sisältöä selaimeesi:', s9i:['Bookmarklet: vedä "Tallenna Forgeen" -painike kirjanmerkkiriviin. Klikkaa sitä millä tahansa sivulla välittömäksi tallennukseksi.','PWA jakamiskohde: matkapuhelimella käytä selaimen natiivia jakovalikkoa lähetettäessä linkkejä BookmarkForgeen.'], s9x2:'Molemmat metodit lähettävät vain URL-osoitteen ja sivun otsikon sovelluksen, kun otat ne eksplisiittisesti käyttöön. Selausaktiivisuutta ei seurata.',
  s10t:'Kolmannen osapuolen palvelut', s10x:'Käytämme seuraavia kolmannen osapuolen palveluita:', s10i:['Google Fonts – typografiaan (fontit välimuistitetaan paikallisesti)','KI-palveluntarjoajat – Google, OpenAI, Anthropic jne. (vain jos määrität ne)'],
  s11t:'Oikeutesi (GDPR)', s11x:'BookmarkForge on suunniteltu siten, että EMME KOSKAAN saa henkilökohtaisia tietojasi, mikä tarkoittaa, että suurin osa GDPR-velvoitteista katoaa suunnittelutasolla. Yleisen tietosuojan asetuksen (GDPR) mukaan säilytät seuraavat oikeudet:', s11i:['Syysintaoikeus (art. 15): kaikki tietosi ovat laitteellasi. Käytä vientitoimintoa saadaksesi täydellisen, koneellisesti luettavan kopion milloin tahansa.','Oikeus oikaisuun (art. 16): muokkaa kirjanmerkkejäsi, muistiinpanojasi ja dokumenttejasi suoraan sovelluksessa.','Oikeus poistoon (art. 17): käytä sisäänrakennettua tietojen poistotoimintoa (Asetukset → Vaara-alue / Nuclear Forget). Tämä poistaa pysyvästi kaikki paikalliset tietoi, mukaan lukien salatut avaimet ja palautustiedot. Me emme säilytä mitään kopiota.','Oikeus siirrettävyyteen (art. 20): viennit käyttävät avoimia formaatteja (JSON, Markdown, HTML), joita voidaan käyttää muissa sovelluksissa.','Oikeus vastustaa ja rajoittaa käsittelyä (art. 18/21): kaikki valinnainen käsittely (pilvi-KI, telemetry, virheraportit) on tiukasti opt-in ja voidaan poistaa käytöstä milloin tahansa Asetuksissa.','Oikeus peruuttaa suostumus (art. 7): valinnaisten toimintojen poistaminen käytöstä Asetuksissa peruuttaa suostumuksen välittömasti ja pysäyttää kaiken siihen liittyvän käsittelyn.'], s11x2:'Käyttääksesi oikeutta, joka vaatii meidän puuttumisemme (esim. valitus palvelimen käsittelystä), ota meihin yhteyttä sähköpostitse kohdassa 17. Sinulla on myös oikeus tehdä valitus kansallisen tietosuojaviranomaisen luona.',
  s12t:'Käyttöperuste ja käsittelyrekisteri', s12x:'GDPR:n 6 artiklan mukaan dokumentoimme kunkin käsittelytoiminnan oikeusperusteen, joka johtaa tietojen poistumiseen laitteeltasi. Rekisteri sisältää: tarkoitukset, rekisteröityjen ryhmät, henkilötietojen kategoriat, vastaanottajat, säilytysajat ja turvallisuustoimenpiteet. Kaikki muut tietosi – kirjanmerkkisi, muistiinpanosi, dokumenttisi, salasanasi – käsitellään yksinomaan laitteellasi hallinnassasi.',
  s13t:'Alihankkijat ja kansainväliset siirrot', s13x:'Käyttäessäsi valinnaisia toimintoja tietoja voidaan käsitellä seuraavien kolmansien osapuolten toimesta (alihankkijat). Jokainen siirto tapahtuu vain, kun käytät toimintoa eksplisiittisesti:', s13i:['Google (Gemini API) – pilvi-KI-promptit ja luodut mediat. Käsittelee tietoja Google Cloudissa. Siirrot EU:n ulkopuolella voivat tapahtua Googlen vakiorahausehtojen nojalla.','OpenAI / Anthropic / Groq / OpenRouter / Hugging Face – vaihtoehtoiset pilvi-KI-palveluntarjoajat, vain jos määrität ne.','Whop – Pro-lisenssimaksu ja oikeuden vahvistus. Whop toimii maksutietojen itsenäisenä rekisterinpitäjinä.','Sentry (Functional Software) – valinnaiset virheraportit, vain jos otat ne käyttöön. Sentry toimii käsittelijänä tietojen käsittelysopimuksen nojalla.'], s13x2:'Emme myy, vuokraa tai jaa tietojasi mainustarkoituksiin. Emme käytä seuranta-evästeitä tai kolmannen osapuolen analytiikkaskriptejä. Kansainväliset siirrot: kun palveluntarjoaja käsittelee tietoja ETA:n ulkopuolella, siirrot perustuvat riittävyydet arvioon tai vakiorahausehtoihin.',
  s14t:'Käsittelytoimintarekisteri (ROPA-yhteenveto)', s14x:'Pidetään käsittelytoimintojen yhteenvetorekisteriä (GDPR:n 30 artikla), joka kattaa: tarkoitukset, rekisteröityjen ryhmät, henkilötietojen kategoriat, vastaanottajat, säilytysajat ja turvallisuustoimenpiteet.',
  s15t:'Alaikäisten yksityisyys', s15x:'BookmarkForge ei ole suunniteltu alle 13-vuotiaille (tai vastaavalle vähimmälle iälle oikeuspiirissäsi). Emme kerää tietoisesti henkilökohtaisia tietoja keneltäkään.',
  s16t:'Muutokset tähän käytäntöön', s16x:'Voimme päivittää tätä tietosuojakäytäntöä ajoittain. Merkittävät muutokset näkyvät yläpuolella olevassa "Viimeksi päivitetty" -päiväyksessä, ja käsittelyyn vaikuttavat muutokset ilmoitetaan sovelluksessa ennen niiden voimaantuloa.',
  s17t:'Yhteystiedot', s17x:'Kysymyksiä yksityisyydestä, rekisteröityjen pyynnöistä tai huolista:', s17i1:'Sähköposti: bookmarkforge@proton.me',
  termsTitle:'Palveluehdot',
  t1t:'Ehtojen hyväksyminen', t1x:'Käyttämällä BookmarkForgea hyväksyt nämä palveluehdot. Jos et ole samaa mieltä, älä käytä sovellusta.',
  t2t:'Palvelun kuvaus', t2x:'BookmarkForge on paikallinen ensimmäisen tietohallintasovellus, jonka avulla voit:', t2i:['Tallentaa ja järjestää kirjanmerkkejä','Luoda ja muokata dokumentteja','Käyttää KI-toimintoja (paikallisesti tai pilvipalveluntarjoajien kautta)','Synkronoida tietoja laitteidesi välillä peer-to-peer -yhteyksillä'],
  t3t:'Paikallinen luonne', t3x:'Ymmärrät ja hyväksyt, että:', t3i:['BookmarkForge toimii kokonaan selaimesi','Kaikki tiedot tallennetaan paikallisesti laitteellasi','Emme isännöi, tallenna tai varmuuskopioi tietojasi palvelimillämme','Sinun vastuullasi on varmuuskopioida tietosi vientitoiminnolla'],
  t4t:'Käyttäjän vastuut', t4x:'Hyväksyt seuraavat:', t4i:['Ylläpidät varmuuskopioita tärkeistä tiedoistasi','Suojellet vaultisi salasanaa (emme voi palauttaa sitä)','Käytät sovellusta sovellettavien lakien mukaisesti','Et käytä sovellusta laittomiin tarkoituksiin'],
  t5t:'KI-toiminnot', t5x:'Käyttäessäsi KI-toimintoja:', t5i:['Olet vastuussa promptiesi sisällöstä','Pilvi-KI-palveluntarjoajilla on omat palveluehtonsa ja tietosuojakäytäntönsä','Emme takaa KI-generoidun sisällön tarkkuutta','Paikalliset KI-mallit vaativat yhteensopivaa laitteistoa (WebGPU-tuki)'],
  t6t:'Vastuun rajoitus', t6x:'BookmarkForge toimitetaan "sellaisenaan" ilman takeita. Emme ole vastuussa:', t6i:['Tietojen häviöstä selaimen välimuistin tyhjennyksen vuoksi','Laitteistovioista','Yhteensopimattomuudesta laitteesi kanssa','Virheistä KI-generoidussa sisällössä'],
  t7t:'Henkinen omistus', t7i:['BookmarkForgen koodi ja suunnittelu ovat tekijänoikeuden alaisia','Sinun sisältösi (kirjanmerkkisi, muistiinpanosi, dokumenttisi) jää sinulle','Emme vaadi omistuutta tietoistasi'],
  t8t:'Lopettaminen', t8x:'Koska BookmarkForge toimii paikallisesti, ei ole tilittä lopetettavaa. Voit lopettaa sovelluksen käytön milloin tahansa sulkemalla selaimesi.',
  t9t:'Sovellettava laki', t9x:'Nämä ehdot ovat sovellettavan lainsäädännön alaisia. Kiistat ratkaistaan toimivaltaisessa oikeusistuimessa.',
  t10t:'Yhteystiedot', t10x:'Kysymyksiä näistä ehdoista:', t10i1:'Sähköposti: bookmarkforge@proton.me',
  footerCopyright:'Kaikki oikeudet pidätetään.'
});

// ============ HE (RTL) ============
existing['he'] = mk('he', {
  title:'מדיניות פרטיות ותנאי שימוש',
  metaDesc:'מדיניות פרטיות ותנאי שימוש של BookmarkForge. הנתונים שלך נשארים על המכשיר שלך. גישה מקומית ראשונה, הצפנה, ידע אפס.',
  lastUpdatedLabel:'עדכון אחרון', lastUpdatedDate:'9 בספטמבר 2026', termsLastUpdatedDate:'23 ביולי 2026',
  privacyTitle:'מדיניות פרטיות',
  s1t:'מחזיק המידע', s1x:'מחזיק המידע המתואר במדיניות זו הוא BookmarkForge (ליצירת קשר ראו סעיף 17). עבור השרת המשלים ותשתית הרישיונות, מפעיל הפריסה פועל כמחזיק מידע.',
  s2t:'מבוא ו_scope', s2x:'BookmarkForge ("אנחנו", "שלנו" או "אותנו") מחויב להגנה על פרטיותך. מדיניות זו מסבירה כיצד אנו מעבדים את הנתונים שלך בעת שימוש באפליקציה שלנו.', s2i1:'עקרון מפתח: BookmarkForge פועל 100% באופן מקומי על המכשיר שלך. הסימניות, ההערות, המסמכים ושיחות ה-AI שלך מאוחסנים במסד הנתונים המקומי של הדפדפן שלך לעולם אינם מועברים לשרתים שלנו.',
  s3t:'נתונים שאיננו אוספים', s3x:'ברצוננו להיות ברורים לגבי מה שאיננו אוספים:', s3i:['אין סימניות או כתובות URL שנשלחות לשרתים שלנו','אין הערות או מסמכים שעוזבים את המכשיר שלך','אין שאילתות AI או תשובות שאנו רושמים','אין היסטוריית גלישה שעוקבים אחריה','אין מידע אישי הנדרש לשימוש באפליקציה','אין ניתוח נתונים שנאסף כברירת מחדל'],
  s4t:'איפה חיים הנתונים שלך', s4x:'כל הנתונים שלך מאוחסנים באופן מקומי בדפדפן שלך באמצעות:', s4i:['IndexedDB – לסימניות, מסמכים והגדרות','אחסון מאובטח – למפתחות מוצפנים וסיסמאות','ذاكرة Service Worker – לעבודה לא מקוונת'], s4x2:'הנתונים שלך לעולם אינם עוזבים את המכשיר שלך אלא אם אתה בוחר במפורש:', s4i2:['מייצא קובץ גיבוי','משתף את הכספת שלך עם מכשיר אחר','משתמש בספק AI ענן (השאילתות שלך עוברות ישירות לספק, לא דרכנו)'],
  s5t:'הצפנה', s5x:'הנתונים שלך מוצפנים באמצעות:', s5i:['הצפנה AES-GCM-256 לכל התוכן השמור','Argon2id (KDF עמיד לזיכרון) למפתחות הנגזרים מסיסמאות','המפתחות נגזרים ומאוחסנים באופן מקומי בדפדפן שלך'], s5x2:'אין לנו גישה למפתחות ההצפנה או לסיסמאות שלך.',
  s6t:'דוחות CSP (Content Security Policy)', s6x:'BookmarkForge משתמש בכותרות CSP למניעת התקפות cross-site scripting והזרקת נתונים. אם הדפדפן שלך חוסם משאב עקב כותרות אלה, הוא שולח אוטומטית דוח הפרה טכני קצר לאותו השרת המשרת את האפליקציה (נקודת קצה /csp-report). המפעיל שומר רק:', s6i:['את מקור המשאב החסום (הנתיב, השאילתה והקטע מוסרים; לעולם אינם מידע אישי שלך)','את הוראת CSP שהופרה','את מקור הדף שבו התרחשה ההפרה','קיבוץ SHA-256 של כתובת ה-IP שלך, המשמש רק להגבלת תדר – כתובת ה-IP שלך לעולם אינה נשמרת'], s6x2:' davranış סטנדרטי של הדפדפן הנדרש ממפרט CSP: הדפדפן שולח דוחות אלה אוטומטית, ללא opt-in של המשתמש, מכיוון שהם חלק ממנגנון האבטחה המגן עליך. לא מצורפים עוגיות, מזהים או היסטוריית גלישה, לעולם אינו כלול תוכן הכספת.',
  s7t:'ספקים', s7x:'בעת שימוש בפונקציות AI:', s7i:['AI מקומי (WebLLM): פועל כולו בדפדפן שלך. אף נתון אינו עוזב את המכשיר שלך.','AI ענן (Gemini,(QIcon, Anthropic וכו׳): השאילתות שלך נשלחות ישירות לספק. אנו אינם יוצרים, מאחסנים או רושמים בקשות אלה. לכל ספק מדיניות פרטיות משלו.'],
  s8t:'דוחות שגיאות אופציונליים (רק עם opt-in)', s8x:'אתה יכול לבחור להפעיל דוחות שגיאות בהגדרות. אם הם מופעלים:', s8i:['אנו מקבלים יומני שגיאות טכניים אנונימיים כשאירעה תקלה באפליקציה','אנו לעולם אינם מקבלים: סימניות, טקסטים, כתובות URL, שאילתות או תוכן אישי כלשהו','נשלחים רק מעקבות מחסנית טכניים ומידע על המכשיר','אתה יכול לבטל זאת בכל עת'],
  s9t:'Bookmarklet PWA ויעד שיתוף', s9x:'BookmarkForge מציע שתי דרכים לשמירת תוכן מהדפדפן שלך:', s9i:['Bookmarklet: גרור את הכפתור "שמור ב-Forge" לסרגל הסימניות. לחץ עליו בכל דף לשמירה מיידית.','יעד שיתוף PWA: במובייל, השתמש בתפריט השיתוף המובנה של הדפדפן שלך לשליחת קישורים אל BookmarkForge.'], s9x2:'שתי השיטות שולחות רק את כתובת ה-URL וכותרת הדף לאפליקציה כשאתה מפעיל אותן במפורש. אין מעקב אחר פעילות גלישה.',
  s10t:'שירותי צד שלישי', s10x:'אנו משתמשים בשירותי צד שלישי הבאים:', s10i:['Google Fonts – לטיפוגרפיה (גופנים מאוחסנים באופן מקומי)','ספק AI – Google, OpenAI, Anthropic וכו׳ (רק אם אתה מגדיר אותם)'],
  s11t:'הזכויות שלך (GDPR)', s11x:'BookmarkForge מעוצב כך שמעולם לא נקבל את הנתונים האישיים שלך, מה שאומר שרוב ההתחייבויות של GDPR נעלמות בעיצוב. בהתאם לתקנת ההגנה הכללית על נתונים (GDPR), אתה שומר על הזכויות הבאות:', s11i:['זכות גישה (סעיף 15): כל הנתונים שלך על המכשיר שלך. השתמש בפונקציית הייצוא כדי לקבל עותק מלא הניתן לקריאת מכונה בכל עת.','זכות תיקון (סעיף 16): ערוך את הסימניות, ההערות והמסמכים שלך ישירות באפליקציה.','זכות מחיקה (סעיף 17): השתמש בפונקציית מחיקת הנתונים המובנית (הגדרות → אזור סכנה / מחיקה גרעינית). זה מוחק לצמיתות את כל הנתונים המקומיים, כולל מפתחות מוצפנים ונתוני שחזור. אנו לא שומרים עותק.','זכות ניידות (סעיף 20): הייצוא משתמש בפורמטים פתוחים (JSON, Markdown, HTML) לשימוש באפליקציות אחרות.','זכות התנגדות והגבלת עיבוד (סעיפים 18/21): כל עיבוד אופציונלי (AI ענן, טלמטריה, דוחות שגיאות) הוא opt-in בלבד וניתן לביטול בכל עת בהגדרות.','זכות ביטול הסכמה (סעיף 7): ביטול פונקציות אופציונליות בהגדרות מבטל את ההסכמה באופן מיידי ועוצר את כל העיבוד המשויך.'], s11x2:'לממש כל זכות הדורשת את התערבותנו (למשל תלונה על עיבוד בשרת), צור איתנו קשר בדוא״ל בסעיף 17. יש לך גם זכות להגיש תלונה לרשות הגנת הנתונים הלאומית שלך.',
  s12t:'בסיס חוקי וسجل עיבוד', s12x:' בהתאם לסעיף 6 של GDPR, אנו מתעדים את הבסיס החוקי לכל פעולת עיבוד שגורמת ליציאת נתונים מהמכשיר שלך. הרישום כולל: מטרות, קטגוריות נושאים, קטגוריות מידע אישי, נמענים, תקופות שמירה ואמצעי אבטחה (הצפנת AES-256-GCM בצד הלקוח, TLS 1.3 בהעברה, אותות חתומים ב-HMAC, הגבלת תדר). כל הנתונים האחרים – הסימניות, ההערות, המסמכים, הסיסמאות שלך – מעובדים אך ורק על המכשיר שלך בשליטתך.',
  s13t:'קבלני משנה והעברות בינלאומיות', s13x:'בעת שימוש בפונקציות אופציונליות, נתונים עשויים להיות מעובדים על ידי צדדים שלישיים הבאים (קבלני משנה). כל העברה מתרחשת רק כשאתה משתמש בפונקציה במפורש:', s13i:['Google (API Gemini) – שאילתות AI בענן ומדיה שנוצרה. מעבד נתונים ב-Google Cloud. העברות מחוץ לאזור הכלכלי האירופי עשויות להתרחש במסגרת סעיפים חוזיים סטנדרטיים של Google.','OpenAI / Anthropic / Groq / OpenRouter / Hugging Face – ספקים חלופיים של AI בענן, רק אם אתה מגדיר אותם.','Whop – תשלום רישיון Pro ואימות זכאות. Whop פועל כמחזיק מידע עצמאי של נתוני תשלום.','Sentry (Functional Software) – דוחות שגיאות אופציונליים, רק אם אתה מפעיל אותם. Sentry פועל כמעבד במסגרת הסכם עיבוד נתונים.'], s13x2:'אינו מוכר, משכיר או משתף את הנתונים שלך למטרות פרסום. אנו אינם משתמשים ב-cookie מעקב או סקריפטים ניתוח של צדדים שלישיים. העברות בינלאומיות: כאשר ספק מעבד נתונים מחוץ לאזור הכלכלי האירופי, ההעברות מבוססות על החלטת התאמה או סעיפים חוזיים סטנדרטיים.',
  s14t:'سجل פעולות עיבוד (סיכום ROPA)', s14x:'מתוחזק רישום מקוצר של פעולות עיבוד (סעיף 30 של GDPR) הכולל: מטרות, קטגוריות נושאים, קטגוריות מידע אישי, נמענים, תקופות שמירה ואמצעי אבטחה.',
  s15t:'פרטיות קטינים', s15x:'BookmarkForge אינו מיועד לילדים מתחת לגיל 13 (או הגיל המינימלי המקביל בתחומי השיפוט שלך). אנו אינם אוספים במודע מידע אישי מאף אחד.',
  s16t:'שינויים במדיניות זו', s16x:'אנו עשויים לעדכן מדיניות זו באופן שוטף. שינויים מהותיים ישתקפו בתאריך "עדכון אחרון" למעלה, ועבור שינויים המשפיעים על העיבוד יוכרזו בתוך האפליקציה לפני כניסתם לתוקף.',
  s17t:'יצירת קשר', s17x:'לשאלות לגבי פרטיות, בקשות נושאים או חששות:', s17i1:'דוא״ל: bookmarkforge@proton.me',
  termsTitle:'תנאי שימוש',
  t1t:'קבלת התנאים', t1x:'בשימוש ב-BookmarkForge אתה מקבל את תנאי שימוש אלה. אם אינך מסכים, אל תשתמש באפליקציה.',
  t2t:'תיאור השירות', t2x:'BookmarkForge הוא אפליקציית ניהול ידע מקומית המאפשרת לך:', t2i:['לשמן ולארגן סימניות','ליצור ולערוך מסמכים','להשתמש בפונקציות AI (מקומית או דרך ספקים בענן)','לסנכרן נתונים בין המכשירים שלך באמצעות חיבור עמית לעמית'],
  t3t:'טבע מקומי', t3x:'אתה מבין ומסכים ש:', t3i:['BookmarkForge פועל כולו בדפדפן שלך','כל הנתונים מאוחסנים באופן מקומי על המכשיר שלך','אינו מאחסנים או מגבים את הנתונים שלך בשרתים שלנו','אתה אחראי לגבות את הנתונים שלך באמצעות פונקציית הייצוא'],
  t4t:'אחריות המשתמש', t4x:'אתה מסכים ל:', t4i:['לשמור גיבויים של הנתונים החשובים שלך','להגן על סיסמת הכספת שלך (אין לנו אפשרות לשחזר אותה)','להשתמש באפליקציה בהתאם לחוקים החלים','לא להשתמש באפליקציה למטרות לא חוקיות'],
  t5t:'פונקציות AI', t5x:'בשימוש בפונקציות AI:', t5i:['אתה אחראי על תוכן השאילתות שלך','ספקים בענן имеют את תנאי השירות ומדיניות הפרטיות שלהם','אינו מבטיחים את הדיוק של תוכן שנוצר על ידי AI','דגמי AI מקומיים דורשים חומרה תואמת (תמיכה ב-WebGPU)'],
  t6t:'הגבלת אחריות', t6x:'BookmarkForge מסופק "כפי שהוא" ללא אחריות מכל סוג. איננו אחראים ל:', t6i:['אובדן נתונים בשל ניקוי מטמון הדפדפן','תקלות חומרה','חוסר תאימות עם המכשיר שלך','שגיאות בתוכן שנוצר על ידי AI'],
  t7t:'קניין רוחני', t7i:['הקוד והעיצוב של BookmarkForge מוגנים בזכויות יוצרים','התוכן שלך (סימניות, הערות, מסמכים) נשאר שלך','אינו תובעים בעלות על הנתונים שלך'],
  t8t:'סיום', t8x:'מכיוון ש-BookmarkForge פועל באופן מקומי, אין חשבון לביטול. אתה יכול להפסיק להשתמש באפליקציה בכל עת על ידי סגירת הדפדפן.',
  t9t:'חוק חל', t9x:'תנאים אלו כפופים לחוק החל. כל מחלוקת תיפתר בבתי המשפט המוסמכים.',
  t10t:'יצירת קשר', t10x:'לשאלות לגבי תנאים אלו:', t10i1:'דוא״ל: bookmarkforge@proton.me',
  footerCopyright:'כל הזכויות שמורות.'
});

writeFileSync(outPath, JSON.stringify(existing, null, 2), 'utf8');
console.log('Added fi, he. Total:', Object.keys(existing).length);
