// Generated by scripts/generate-license-keys.mjs — DO NOT EDIT BY HAND.
// New keypair: node scripts/generate-license-keys.mjs --write
// Sync only:   node scripts/generate-license-keys.mjs --sync-server-key
// Gate:        npm run check:license-keys  (fails when this file and the
//              committed client key src/services/licenseKeys.ts differ)
//
// PUBLIC VERIFICATION KEY ONLY. The API image copies just `server/`, so the
// server keeps its own copy of the key instead of importing the client
// module; check:license-keys is what stops the two from drifting.
export const LICENSE_PUBLIC_KEY_SPKI =
  "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuTSUMP/aVL5NWM+XeujNElLe7cjscfgsjrrMqXqQveJBNBpdo9wJW8jDCcoHjtpWxNF+YCcbknhYWpGtz8TZ+7kDt2+dSzHR8q0zUTCeiK80PxZftlOqj1D8oDo3bz0GczLFTbV+2iikKOt3YBp3OWgMm8QrSYCOP8CjDibR9mz53SHKxragO6l9GG4ZeR+2DUHNgw6LpROMFpvDax+XyQU4hRHmjmGy4kwbp9aYg5pj93YEAKAPitHn44s2zWXyY3EYN8I4JpGrsJTPTSD9xNp+hUmDs2vmH5U2Bici144vAiZyRQIN+JrJuAjvrj6myekPPtbMxMo3JgM7PLIHoQIDAQAB";
