#!/usr/bin/env node

/**
 * Whop Configuration Script
 * 
 * This script automates the configuration of Whop integration for BookmarkForge:
 * - Validates Whop API key
 * - Retrieves product and plan information
 * - Configures environment variables
 * - Tests connection to Whop API
 * 
 * What this script CANNOT do (must be done manually in Whop Dashboard):
 * - Create products (manual: Whop Dashboard → Products → Create Product)
 * - Create plans (manual: Whop Dashboard → Products → Create Plan)
 * - Configure webhooks (manual: Whop Dashboard → Developer → Webhooks)
 * 
 * Usage:
 *   node scripts/whop-config.mjs
 * 
 * Environment variables:
 *   WHOP_API_KEY - Your Whop Account API Key (required)
 *   WHOP_PRODUCT_ID - Product ID from Whop Dashboard (required)
 *   WHOP_PLAN_LIFETIME - Plan ID for LIFETIME plan (required)
 *   WHOP_WEBHOOK_SECRET - Webhook secret (optional)
 */

import https from 'https';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Configuration
const WHOP_API_BASE = 'https://api.whop.com/api/v1';

// Get environment variables
const WHOP_API_KEY = process.env.WHOP_API_KEY;
const WHOP_PRODUCT_ID = process.env.WHOP_PRODUCT_ID;
const WHOP_PLAN_LIFETIME = process.env.WHOP_PLAN_LIFETIME;
const WHOP_WEBHOOK_SECRET = process.env.WHOP_WEBHOOK_SECRET || '';

// Validate required environment variables
if (!WHOP_API_KEY) {
  console.error('❌ Error: WHOP_API_KEY environment variable is required');
  console.error('Get your API key from: https://whop.com/dashboard → Developer → API Keys');
  process.exit(1);
}

console.log('🔧 Whop Configuration Script');
console.log('=================================\n');
console.log(`📦 API Key: ${WHOP_API_KEY.substring(0, 8)}...${WHOP_API_KEY.substring(WHOP_API_KEY.length - 4)}`);
console.log(`📦 Product ID: ${WHOP_PRODUCT_ID || 'Not provided'}`);
console.log(`📦 Plan ID: ${WHOP_PLAN_LIFETIME || 'Not provided'}`);
console.log(`📦 Webhook Secret: ${WHOP_WEBHOOK_SECRET ? 'Provided' : 'Not provided'}\n`);

/**
 * Make an authenticated request to Whop API
 */
async function whopRequest(endpoint, method = 'GET', body = null) {
  const url = `${WHOP_API_BASE}${endpoint}`;
  const options = {
    method,
    headers: {
      'Authorization': `Bearer ${WHOP_API_KEY}`,
      'Content-Type': 'application/json',
    },
  };

  return new Promise((resolve, reject) => {
    const req = https.request(url, options, (res) => {
      let data = '';

      res.on('data', (chunk) => {
        data += chunk;
      });

      res.on('end', () => {
        try {
          const parsed = JSON.parse(data);
          if (res.statusCode >= 200 && res.statusCode < 300) {
            resolve(parsed);
          } else {
            reject(new Error(`Whop API error: ${res.statusCode} - ${parsed.message || data}`));
          }
        } catch {
          // Not JSON (e.g. an empty 2xx body): surface the raw payload.
          resolve(data);
        }
      });
    });

    req.on('error', reject);

    if (body) {
      req.write(JSON.stringify(body));
    }

    req.end();
  });
}

/**
 * Test API key by fetching products list
 */
async function testApiKey() {
  console.log('🔍 Testing Whop API key...');
  
  try {
    const result = await whopRequest('/products');
    console.log('✅ API key is valid');
    console.log(`   Products found: ${result.data?.length || 0}`);
    return true;
  } catch (error) {
    console.error(`❌ API key validation failed: ${error.message}`);
    return false;
  }
}

/**
 * Fetch product information
 */
async function fetchProduct(productId) {
  console.log(`📋 Fetching product ${productId}...`);
  
  try {
    const result = await whopRequest(`/products/${productId}`);
    console.log('✅ Product found');
    console.log(`   Name: ${result.data?.name || 'Unknown'}`);
    console.log(`   ID: ${result.data?.id || 'Unknown'}`);
    return result.data;
  } catch (error) {
    console.error(`❌ Product fetch failed: ${error.message}`);
    return null;
  }
}

/**
 * Fetch plan information
 */
async function fetchPlan(planId) {
  console.log(`📋 Fetching plan ${planId}...`);
  
  try {
    const result = await whopRequest(`/plans/${planId}`);
    console.log('✅ Plan found');
    console.log(`   Name: ${result.data?.name || 'Unknown'}`);
    console.log(`   ID: ${result.data?.id || 'Unknown'}`);
    console.log(`   Price: $${result.data?.price || 'Unknown'}`);
    return result.data;
  } catch (error) {
    console.error(`❌ Plan fetch failed: ${error.message}`);
    return null;
  }
}

/**
 * Generate .env.whop file
 */
function generateEnvFile() {
  const envContent = `# Whop.com Configuration
# Generated by scripts/whop-config.mjs

# Whop Account API Key (Server-side only - never expose to client)
WHOP_API_KEY=${WHOP_API_KEY}

# Whop Product ID for BookmarkForge Pro
WHOP_PRODUCT_ID=${WHOP_PRODUCT_ID || 'prod_xxxxxxxxxxxxxx'}

# Whop Plan ID for BookmarkForge Pro LIFETIME
WHOP_PLAN_LIFETIME=${WHOP_PLAN_LIFETIME || 'plan_xxxxxxxxxxxxxx'}

# Whop Trial Duration (days)
WHOP_TRIAL_DURATION_DAYS=7

# Whop Trial Price (0 = free trial)
WHOP_TRIAL_PRICE=0

# Whop Webhook Secret (for webhook verification)
WHOP_WEBHOOK_SECRET=${WHOP_WEBHOOK_SECRET || 'your_webhook_secret_here'}

# Environment
WHOP_ENVIRONMENT=production

# Checkout URL (for user-facing purchase flow)
VITE_WHOP_CHECKOUT_URL=https://bookmarkforgeapp.com/checkout
`;

  const envPath = path.join(__dirname, '..', '.env.whop');
  fs.writeFileSync(envPath, envContent);
  console.log(`\n✅ Generated .env.whop file at: ${envPath}`);
}

/**
 * Display configuration summary
 */
function displaySummary(product, plan) {
  console.log('\n═══════════════════════════════════════════════════════════════');
  console.log('              WHOP CONFIGURATION SUMMARY');
  console.log('═══════════════════════════════════════════════════════════════\n');

  console.log('API Key:');
  console.log(`  ✅ Valid: ${WHOP_API_KEY.substring(0, 8)}...${WHOP_API_KEY.substring(WHOP_API_KEY.length - 4)}\n`);

  if (product) {
    console.log('Product:');
    console.log(`  ✅ Name: ${product.name}`);
    console.log(`  ✅ ID: ${product.id}\n`);
  } else {
    console.log('Product:');
    console.log(`  ⚠️  Not configured or invalid\n`);
  }

  if (plan) {
    console.log('Plan:');
    console.log(`  ✅ Name: ${plan.name}`);
    console.log(`  ✅ ID: ${plan.id}`);
    console.log(`  ✅ Price: $${plan.price}\n`);
  } else {
    console.log('Plan:');
    console.log(`  ⚠️  Not configured or invalid\n`);
  }

  console.log('Next Steps:');
  console.log('  1. Copy .env.whop to .env.production');
  console.log('  2. Add the same values to GitHub Secrets (for deployment)');
  console.log('  3. Configure webhooks in Whop Dashboard (optional but recommended)');
  console.log('  4. Test the integration with a test purchase');

  console.log('\n═══════════════════════════════════════════════════════════════\n');
}

/**
 * Main execution
 */
async function main() {
  try {
    // Step 1: Test API key
    const apiKeyValid = await testApiKey();
    if (!apiKeyValid) {
      console.error('\n❌ Cannot proceed without valid API key');
      process.exit(1);
    }

    // Step 2: Fetch product if provided
    let product = null;
    if (WHOP_PRODUCT_ID) {
      product = await fetchProduct(WHOP_PRODUCT_ID);
    } else {
      console.log('⚠️  WHOP_PRODUCT_ID not provided - skipping product validation');
      console.log('   Get it from: Whop Dashboard → Products → BookmarkForge Pro\n');
    }

    // Step 3: Fetch plan if provided
    let plan = null;
    if (WHOP_PLAN_LIFETIME) {
      plan = await fetchPlan(WHOP_PLAN_LIFETIME);
    } else {
      console.log('⚠️  WHOP_PLAN_LIFETIME not provided - skipping plan validation');
      console.log('   Get it from: Whop Dashboard → Products → BookmarkForge Pro → Plans → LIFETIME\n');
    }

    // Step 4: Generate .env.whop file
    generateEnvFile();

    // Step 5: Display summary
    displaySummary(product, plan);

    console.log('✅ Whop configuration completed successfully!');
    console.log('\n📝 Manual steps still required:');
    console.log('   - Create product in Whop Dashboard (if not already done)');
    console.log('   - Create LIFETIME plan in Whop Dashboard (if not already done)');
    console.log('   - Configure webhooks in Whop Dashboard (optional but recommended)');
    console.log('   - Copy .env.whop to .env.production');
    console.log('   - Add values to GitHub Secrets (for deployment)\n');

  } catch (error) {
    console.error('\n❌ Whop configuration failed:', error.message);
    process.exit(1);
  }
}

// Run the script
main();
